import { AppContentModule } from '../generated/prisma/enums';
import type { DefaultContent } from './app-content.defaults.types';

export const SUPPORT_DEFAULTS: DefaultContent[] = [
  // SUPPORT (customer-facing en/hi + ops zh)
  {
    module: AppContentModule.SUPPORT,
    key: 'header_title',
    body: 'Online Customer Service',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'header_title',
    body: 'ऑनलाइन ग्राहक सेवा',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'fab_label',
    body: 'Customer Service',
    locale: 'en',
    sortOrder: 6,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'fab_label',
    body: 'ग्राहक सेवा',
    locale: 'hi',
    sortOrder: 6,
  },

  {
    module: AppContentModule.SUPPORT,
    key: 'greeting',
    body: 'You are contacting online customer service inside the app.',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'greeting',
    body: 'आप ऐप के अंदर ऑनलाइन ग्राहक सेवा से संपर्क कर रहे हैं।',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'hours',
    body: 'Online customer service hours: Mon-Sun 09:00-22:00 (IST). We are here to help with deposits, trading and account questions.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'hours',
    body: 'ऑनलाइन ग्राहक सेवा समय: सोम-रवि 09:00-22:00 (IST)। जमा, ट्रेडिंग और खाते में सहायता के लिए हम उपलब्ध हैं।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_topics_label',
    body: 'Quick topics',
    locale: 'en',
    sortOrder: 22,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_topics_label',
    body: 'त्वरित विषय',
    locale: 'hi',
    sortOrder: 22,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.deposit',
    body: 'Deposit',
    locale: 'en',
    sortOrder: 24,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.deposit',
    body: 'जमा',
    locale: 'hi',
    sortOrder: 24,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.trading',
    body: 'Trading',
    locale: 'en',
    sortOrder: 25,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.trading',
    body: 'ट्रेडिंग',
    locale: 'hi',
    sortOrder: 25,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.account',
    body: 'Account',
    locale: 'en',
    sortOrder: 26,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.account',
    body: 'खाता',
    locale: 'hi',
    sortOrder: 26,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'composer_hint',
    body: 'Use a topic or open on mobile',
    locale: 'en',
    sortOrder: 28,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'composer_hint',
    body: 'विषय चुनें या मोबाइल पर खोलें',
    locale: 'hi',
    sortOrder: 28,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.help',
    body: 'Hello, I need help with my account.',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.help',
    body: 'नमस्ते, मुझे अपने खाते में सहायता चाहिए।',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.deposit',
    body: 'Hello, I have completed / want to make a deposit. Please share payment details. Finance will credit my account after confirmation.',
    locale: 'en',
    sortOrder: 35,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.deposit',
    body: 'नमस्ते, मैं अपने खाते में पैसे जोड़ना चाहता/चाहती हूँ।',
    locale: 'hi',
    sortOrder: 35,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'salesmartly_script_url',
    // Intentionally empty: production must set CMS or SALESMARTLY_SCRIPT_URL.
    // Do not ship a concrete tenant project_*.js as a silent fallback.
    body: '',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'salesmartly_script_url',
    body: '',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'tags',
    body: '入金咨询,提现问题,KYC,交易问题,账户问题,紧急,已跟进',
    locale: 'zh',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.deposit',
    title: '入金指引',
    body: '您好，请按客服提供的存款方式付款并发送付款凭证。客服会转交信息，财务核实实际到账后为账户上分。',
    locale: 'zh',
    sortOrder: 50,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.withdrawal',
    title: '提现跟进',
    body: '您的提现申请已收到，财务会根据订单号核对并处理。',
    locale: 'zh',
    sortOrder: 60,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.kyc',
    title: 'KYC 审核',
    body: '请上传清晰的 Aadhaar 或 PAN 文件，业务员会尽快审核 KYC。',
    locale: 'zh',
    sortOrder: 70,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.general',
    title: '通用核查',
    body: '请提供手机号、客户姓名和问题截图，我们马上为您核查。',
    locale: 'zh',
    sortOrder: 80,
  },
];
