import { AppContentModule } from '../generated/prisma/enums';
import type { DefaultContent } from './app-content.defaults.types';

export const DEPOSIT_DEFAULTS: DefaultContent[] = [
  // DEPOSIT (copy only — no receiving / bank accounts)
  {
    module: AppContentModule.DEPOSIT,
    key: 'hero_title',
    body: 'Fund your trading account',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'hero_title',
    body: 'अपने ट्रेडिंग खाते में राशि जोड़ें',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'instructions',
    title: 'Deposit instructions',
    body: 'Contact support for payment details, then transfer. Finance credits your trading balance after payment is confirmed. Deposits are not submitted inside the app.',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'instructions',
    title: 'जमा निर्देश',
    body: 'कृपया जमा निर्देशों के लिए ऑनलाइन सहायता से संपर्क करें। भुगतान की पुष्टि के बाद वित्त टीम आपके खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'cta_label',
    body: 'Contact customer support',
    locale: 'en',
    sortOrder: 15,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'cta_label',
    body: 'ग्राहक सहायता से संपर्क करें',
    locale: 'hi',
    sortOrder: 15,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'chat_preset',
    body: 'Hello, I have completed / want to make a deposit. Please share payment details. Finance will credit my account after confirmation.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'chat_preset',
    body: 'नमस्ते, मैं जमा करना चाहता/चाहती हूँ। कृपया भुगतान विवरण दें। पुष्टि के बाद वित्त टीम खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'api_reject_message',
    body: 'Contact support for payment details, then transfer. Finance credits your trading balance after payment is confirmed. Deposits are not submitted inside the app.',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'api_reject_message',
    body: 'कृपया जमा निर्देशों के लिए ऑनलाइन सहायता से संपर्क करें। भुगतान की पुष्टि के बाद वित्त टीम आपके खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_empty',
    body: 'No deposit records yet.',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_empty',
    body: 'अभी कोई जमा रिकॉर्ड नहीं है।',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms',
    body: '• Verify the beneficiary details with Online Customer Service before transferring.\n\n• Deposits are credited only after finance confirmation.\n\n• Keep your transfer receipt for settlement support.',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms',
    body: '• स्थानांतरण से पहले ऑनलाइन ग्राहक सेवा से लाभार्थी विवरण सत्यापित करें।\n\n• वित्त पुष्टि के बाद ही जमा जमा होती है।\n\n• निपटान सहायता के लिए स्थानांतरण रसीद सुरक्षित रखें।',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'page_title',
    body: 'Deposit',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'page_title',
    body: 'जमा',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_section_title',
    body: 'DEPOSIT HISTORY',
    locale: 'en',
    sortOrder: 56,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_section_title',
    body: 'जमा इतिहास',
    locale: 'hi',
    sortOrder: 56,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms_section_title',
    body: 'TERMS',
    locale: 'en',
    sortOrder: 57,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms_section_title',
    body: 'शर्तें',
    locale: 'hi',
    sortOrder: 57,
  },
];
