import { AppContentModule } from '../generated/prisma/enums';
import type { DefaultContent } from './app-content.defaults.types';

export const HOME_DEFAULTS: DefaultContent[] = [
  // HOME
  {
    module: AppContentModule.HOME,
    key: 'ui.copy',
    body: '{}',
    locale: 'en',
    sortOrder: 1,
  },
  {
    module: AppContentModule.HOME,
    key: 'ui.copy',
    body: '{}',
    locale: 'hi',
    sortOrder: 1,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.title',
    body: 'Notifications',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.title',
    body: 'सूचनाएँ',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.loading',
    body: 'Loading notifications',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.loading',
    body: 'सूचनाएँ लोड हो रही हैं',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.load_error',
    body: 'Unable to load notifications',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.load_error',
    body: 'सूचनाएँ लोड नहीं हो सकीं',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.load_error_body',
    body: 'The server did not return notifications. You can retry.',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.load_error_body',
    body: 'सर्वर से सूचनाएँ नहीं मिलीं। आप फिर प्रयास कर सकते हैं।',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.empty_title',
    body: 'No notifications yet',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.empty_title',
    body: 'अभी कोई सूचना नहीं है',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.empty_body',
    body: 'Account and order updates will appear here when the server sends them.',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.empty_body',
    body: 'खाता और ऑर्डर अपडेट मिलने पर वे यहाँ दिखाई देंगे।',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.recent',
    body: 'Recent updates',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.recent',
    body: 'हाल के अपडेट',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.caught_up',
    body: 'All caught up',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.caught_up',
    body: 'सभी सूचनाएँ पढ़ ली गई हैं',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.unread_count',
    body: '{count} unread',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.unread_count',
    body: '{count} अपठित',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.mark_read_error',
    body: 'Unable to mark notification as read',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.mark_read_error',
    body: 'सूचना को पढ़ा हुआ चिह्नित नहीं किया जा सका',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.mark_all_error',
    body: 'Unable to mark all notifications',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.mark_all_error',
    body: 'सभी सूचनाओं को पढ़ा हुआ चिह्नित नहीं किया जा सका',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.marking',
    body: 'Marking notifications as read',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.marking',
    body: 'सूचनाओं को पढ़ा हुआ चिह्नित किया जा रहा है',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.unread',
    body: 'Unread',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'notifications.unread',
    body: 'अपठित',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.title',
    body: 'Track live markets & place orders on the go',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.title',
    body: 'लाइव बाज़ार ट्रैक करें और कहीं से भी ऑर्डर दें',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.subtitle',
    body: 'Explore equities, institutional offers, OTC and IPOs',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.subtitle',
    body: 'इक्विटी, संस्थागत प्रस्ताव, ओटीसी और आईपीओ देखें',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.title',
    body: 'Track live markets & place orders on the go',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.title',
    body: 'लाइव बाज़ार ट्रैक करें और कहीं से भी ऑर्डर दें',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.subtitle',
    body: 'Live prices, company logos and secure execution',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.subtitle',
    body: 'लाइव कीमतें, कंपनी लोगो और सुरक्षित निष्पादन',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.loading',
    body: 'Loading markets…',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.loading',
    body: 'बाज़ार लोड हो रहे हैं…',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.watchlist_error_title',
    body: 'Unable to load watchlist',
    locale: 'en',
    sortOrder: 41,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.watchlist_error_title',
    body: 'वॉचलिस्ट लोड नहीं हो सकी',
    locale: 'hi',
    sortOrder: 41,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.watchlist_error_body',
    body: 'Watchlist data is unavailable. Please try again.',
    locale: 'en',
    sortOrder: 42,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.watchlist_error_body',
    body: 'वॉचलिस्ट डेटा उपलब्ध नहीं है। कृपया फिर प्रयास करें।',
    locale: 'hi',
    sortOrder: 42,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_error_title',
    body: 'Market data unavailable',
    locale: 'en',
    sortOrder: 43,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_error_title',
    body: 'बाज़ार डेटा उपलब्ध नहीं है',
    locale: 'hi',
    sortOrder: 43,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_error_body',
    body: 'Network error or live search is unavailable. Please refresh to try again.',
    locale: 'en',
    sortOrder: 44,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_error_body',
    body: 'नेटवर्क में समस्या है या लाइव खोज उपलब्ध नहीं है। कृपया रीफ़्रेश करके फिर प्रयास करें।',
    locale: 'hi',
    sortOrder: 44,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.load_more',
    body: 'Load more',
    locale: 'en',
    sortOrder: 45,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.load_more',
    body: 'और देखें',
    locale: 'hi',
    sortOrder: 45,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.load_more_retry',
    body: 'Unable to load stocks. Retry',
    locale: 'en',
    sortOrder: 46,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.load_more_retry',
    body: 'स्टॉक लोड नहीं हो सके। फिर प्रयास करें',
    locale: 'hi',
    sortOrder: 46,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.refresh',
    body: 'Refresh market data',
    locale: 'en',
    sortOrder: 47,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.refresh',
    body: 'बाज़ार डेटा रीफ़्रेश करें',
    locale: 'hi',
    sortOrder: 47,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.title',
    body: 'Search stocks',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.title',
    body: 'स्टॉक खोजें',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.hint',
    body: 'Search symbol or company',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.hint',
    body: 'प्रतीक या कंपनी खोजें',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.searching',
    body: 'Searching stocks…',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.searching',
    body: 'स्टॉक खोजे जा रहे हैं…',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.watchlist_update_error',
    body: 'Unable to update watchlist',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.watchlist_update_error',
    body: 'वॉचलिस्ट अपडेट नहीं हो सकी',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.partial_error',
    body: 'Live search is unavailable. Showing loaded instruments.',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.partial_error',
    body: 'लाइव खोज उपलब्ध नहीं है। पहले से लोड किए गए साधन दिखाए जा रहे हैं।',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.more_error',
    body: 'More results could not be loaded. Your current results are still available.',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.more_error',
    body: 'और परिणाम लोड नहीं हो सके। मौजूदा परिणाम अभी भी उपलब्ध हैं।',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.error_title',
    body: 'Unable to load stocks',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.error_title',
    body: 'स्टॉक लोड नहीं हो सके',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.error_body',
    body: 'Search is temporarily unavailable. Please retry.',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.error_body',
    body: 'खोज अस्थायी रूप से उपलब्ध नहीं है। कृपया फिर प्रयास करें।',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.empty_title',
    body: 'No instruments available',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.empty_title',
    body: 'कोई साधन उपलब्ध नहीं है',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.empty_body',
    body: 'Try again when market data is available.',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.empty_body',
    body: 'बाज़ार डेटा उपलब्ध होने पर फिर प्रयास करें।',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.no_match_title',
    body: 'No matching stocks',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.no_match_title',
    body: 'कोई मिलता-जुलता स्टॉक नहीं मिला',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.no_match_body',
    body: 'Try a different symbol or company name.',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.no_match_body',
    body: 'कोई दूसरा प्रतीक या कंपनी नाम आज़माएँ।',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.loading_more',
    body: 'Loading…',
    locale: 'en',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.search_page.loading_more',
    body: 'लोड हो रहा है…',
    locale: 'hi',
    sortOrder: 48,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.section_title',
    body: 'Our Company',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.section_title',
    body: 'हमारी कंपनी',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.video_cta',
    body: 'Watch our company introduction',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.video_cta',
    body: 'हमारी कंपनी का परिचय देखें',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.website_cta',
    body: 'Visit website',
    locale: 'en',
    sortOrder: 60,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.website_cta',
    body: 'वेबसाइट देखें',
    locale: 'hi',
    sortOrder: 60,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_label',
    body: 'Add Funds',
    locale: 'en',
    sortOrder: 65,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_label',
    body: 'राशि जोड़ें',
    locale: 'hi',
    sortOrder: 65,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_subtitle',
    body: 'Funding Assistance',
    locale: 'en',
    sortOrder: 70,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_subtitle',
    body: 'जमा सहायता',
    locale: 'hi',
    sortOrder: 70,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.section_title',
    body: 'Market News',
    locale: 'en',
    sortOrder: 75,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.section_title',
    body: 'बाज़ार समाचार',
    locale: 'hi',
    sortOrder: 75,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.empty',
    body: 'Live market news is temporarily unavailable.',
    locale: 'en',
    sortOrder: 80,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.empty',
    body: 'लाइव बाज़ार समाचार अस्थायी रूप से उपलब्ध नहीं है।',
    locale: 'hi',
    sortOrder: 80,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.page_empty_title',
    body: 'Market news is unavailable',
    locale: 'en',
    sortOrder: 80,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.page_empty_title',
    body: 'बाज़ार समाचार उपलब्ध नहीं हैं',
    locale: 'hi',
    sortOrder: 80,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.page_empty_body',
    body: 'Headlines will appear when the market news feed is available.',
    locale: 'en',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.page_empty_body',
    body: 'बाज़ार समाचार फ़ीड उपलब्ध होने पर सुर्खियाँ यहाँ दिखाई देंगी।',
    locale: 'hi',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.refresh',
    body: 'Refresh',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.refresh',
    body: 'रीफ़्रेश करें',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.refresh_error',
    body: 'News could not be updated. Please try again.',
    locale: 'en',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.refresh_error',
    body: 'समाचार अपडेट नहीं हो सके। कृपया फिर प्रयास करें।',
    locale: 'hi',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_label',
    body: 'Withdraw Funds',
    locale: 'en',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_label',
    body: 'राशि निकालें',
    locale: 'hi',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_subtitle',
    body: 'Transfer to Bank',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_subtitle',
    body: 'बैंक में स्थानांतरित करें',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_label',
    body: 'Trade',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_label',
    body: 'ट्रेड',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_subtitle',
    body: 'Place orders',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_subtitle',
    body: 'ऑर्डर दें',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.total_asset_label',
    body: 'Total Asset Value',
    locale: 'en',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.total_asset_label',
    body: 'कुल परिसंपत्ति मूल्य',
    locale: 'hi',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.available_label',
    body: 'Available Balance',
    locale: 'en',
    sortOrder: 84,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.available_label',
    body: 'उपलब्ध शेष',
    locale: 'hi',
    sortOrder: 84,
  },
  {
    module: AppContentModule.HOME,
    key: 'indices.section_title',
    body: 'Market Indices',
    locale: 'en',
    sortOrder: 85,
  },
  {
    module: AppContentModule.HOME,
    key: 'indices.section_title',
    body: 'बाज़ार सूचकांक',
    locale: 'hi',
    sortOrder: 85,
  },
  {
    module: AppContentModule.HOME,
    key: 'view_all_cta',
    body: 'View All',
    locale: 'en',
    sortOrder: 86,
  },
  {
    module: AppContentModule.HOME,
    key: 'view_all_cta',
    body: 'सभी देखें',
    locale: 'hi',
    sortOrder: 86,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.page_title',
    body: 'Profile',
    locale: 'en',
    sortOrder: 90,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.page_title',
    body: 'प्रोफ़ाइल',
    locale: 'hi',
    sortOrder: 90,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.overview',
    body: 'Account Overview',
    locale: 'en',
    sortOrder: 91,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.overview',
    body: 'खाता अवलोकन',
    locale: 'hi',
    sortOrder: 91,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.account',
    body: 'Account',
    locale: 'en',
    sortOrder: 92,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.account',
    body: 'खाता',
    locale: 'hi',
    sortOrder: 92,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.funds',
    body: 'Funds',
    locale: 'en',
    sortOrder: 93,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.funds',
    body: 'फंड',
    locale: 'hi',
    sortOrder: 93,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.security',
    body: 'Security',
    locale: 'en',
    sortOrder: 94,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.security',
    body: 'सुरक्षा',
    locale: 'hi',
    sortOrder: 94,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.preferences',
    body: 'Preferences',
    locale: 'en',
    sortOrder: 95,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.preferences',
    body: 'प्राथमिकताएँ',
    locale: 'hi',
    sortOrder: 95,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.support',
    body: 'Support & Education',
    locale: 'en',
    sortOrder: 96,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.support',
    body: 'सहायता और शिक्षा',
    locale: 'hi',
    sortOrder: 96,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.legal',
    body: 'Legal',
    locale: 'en',
    sortOrder: 97,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.legal',
    body: 'कानूनी',
    locale: 'hi',
    sortOrder: 97,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.available',
    body: 'Available Balance',
    locale: 'en',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.available',
    body: 'उपलब्ध शेष',
    locale: 'hi',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.portfolio',
    body: 'Product Holdings',
    locale: 'en',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.portfolio',
    body: 'उत्पाद होल्डिंग',
    locale: 'hi',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.returns',
    body: 'Total Returns',
    locale: 'en',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.returns',
    body: 'कुल रिटर्न',
    locale: 'hi',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.title',
    body: 'Help & Support',
    locale: 'en',
    sortOrder: 98,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.title',
    body: 'सहायता और समर्थन',
    locale: 'hi',
    sortOrder: 98,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.subtitle',
    body: 'FAQs, contact support and raise a ticket',
    locale: 'en',
    sortOrder: 99,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.subtitle',
    body: 'प्रश्नोत्तर, सहायता से संपर्क और टिकट',
    locale: 'hi',
    sortOrder: 99,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.title',
    body: 'Wealth Insights',
    locale: 'en',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.title',
    body: 'वेल्थ इनसाइट्स',
    locale: 'hi',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.subtitle',
    body: 'Knowledge for informed investment decisions',
    locale: 'en',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.subtitle',
    body: 'सूचित निवेश निर्णयों के लिए ज्ञान',
    locale: 'hi',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.title',
    body: 'About Us',
    locale: 'en',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.title',
    body: 'हमारे बारे में',
    locale: 'hi',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.subtitle',
    body: 'About our app, terms and policies',
    locale: 'en',
    sortOrder: 103,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.subtitle',
    body: 'ऐप, नियम और नीतियाँ',
    locale: 'hi',
    sortOrder: 103,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.risk.title',
    body: 'Risk Disclosure',
    locale: 'en',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.risk.title',
    body: 'जोखिम प्रकटीकरण',
    locale: 'hi',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.terms.title',
    body: 'Terms & Conditions',
    locale: 'en',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.terms.title',
    body: 'नियम और शर्तें',
    locale: 'hi',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.privacy.title',
    body: 'Privacy Policy',
    locale: 'en',
    sortOrder: 105,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.privacy.title',
    body: 'गोपनीयता नीति',
    locale: 'hi',
    sortOrder: 105,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_label',
    body: 'Logout',
    locale: 'en',
    sortOrder: 106,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_label',
    body: 'लॉग आउट',
    locale: 'hi',
    sortOrder: 106,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_subtitle',
    body: 'Securely logout from your account',
    locale: 'en',
    sortOrder: 107,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_subtitle',
    body: 'अपने खाते से सुरक्षित रूप से लॉग आउट करें',
    locale: 'hi',
    sortOrder: 107,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.dialog_title',
    body: 'Withdrawal Request',
    locale: 'en',
    sortOrder: 110,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.dialog_title',
    body: 'निकासी अनुरोध',
    locale: 'hi',
    sortOrder: 110,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.available_label',
    body: 'Available Funds',
    locale: 'en',
    sortOrder: 111,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.available_label',
    body: 'उपलब्ध राशि',
    locale: 'hi',
    sortOrder: 111,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.frozen_template',
    body: 'Total frozen: {amount}',
    locale: 'en',
    sortOrder: 112,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.frozen_template',
    body: 'कुल रोकी गई राशि: {amount}',
    locale: 'hi',
    sortOrder: 112,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.amount_label',
    body: 'Withdrawal Amount',
    locale: 'en',
    sortOrder: 113,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.amount_label',
    body: 'निकासी राशि',
    locale: 'hi',
    sortOrder: 113,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_hint',
    body: 'Minimum withdrawal: ₹100',
    locale: 'en',
    sortOrder: 114,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_hint',
    body: 'न्यूनतम निकासी: ₹100',
    locale: 'hi',
    sortOrder: 114,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_label',
    body: 'Withdrawal PIN',
    locale: 'en',
    sortOrder: 115,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_label',
    body: 'निकासी पिन',
    locale: 'hi',
    sortOrder: 115,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_section_title',
    body: 'Withdrawal Bank Account',
    locale: 'en',
    sortOrder: 116,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_section_title',
    body: 'निकासी बैंक खाता',
    locale: 'hi',
    sortOrder: 116,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_picker_label',
    body: 'Bank account',
    locale: 'en',
    sortOrder: 117,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_picker_label',
    body: 'बैंक खाता',
    locale: 'hi',
    sortOrder: 117,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.holder_label',
    body: 'Account Holder',
    locale: 'en',
    sortOrder: 118,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.holder_label',
    body: 'खाताधारक',
    locale: 'hi',
    sortOrder: 118,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.account_label',
    body: 'Bank Account',
    locale: 'en',
    sortOrder: 119,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.account_label',
    body: 'बैंक खाता संख्या',
    locale: 'hi',
    sortOrder: 119,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.status_label',
    body: 'Bank Status',
    locale: 'en',
    sortOrder: 120,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.status_label',
    body: 'बैंक स्थिति',
    locale: 'hi',
    sortOrder: 120,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.notice',
    body: 'Your withdrawal request will be submitted for review. The requested amount is frozen immediately. Approval deducts it from your cash balance; rejection releases it.',
    locale: 'en',
    sortOrder: 121,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.notice',
    body: 'आपका निकासी अनुरोध समीक्षा के लिए भेजा जाएगा। अनुरोधित राशि तुरंत रोक दी जाती है। स्वीकृति पर नकदी से कटती है; अस्वीकृति पर मुक्त होती है।',
    locale: 'hi',
    sortOrder: 121,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.records_title',
    body: 'Withdrawal Records',
    locale: 'en',
    sortOrder: 122,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.records_title',
    body: 'निकासी रिकॉर्ड',
    locale: 'hi',
    sortOrder: 122,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.cancel',
    body: 'Cancel',
    locale: 'en',
    sortOrder: 123,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.cancel',
    body: 'रद्द करें',
    locale: 'hi',
    sortOrder: 123,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.submit',
    body: 'Submit Request',
    locale: 'en',
    sortOrder: 124,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.submit',
    body: 'अनुरोध जमा करें',
    locale: 'hi',
    sortOrder: 124,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_incomplete',
    body: 'Complete your bank account details before withdrawing',
    locale: 'en',
    sortOrder: 125,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_incomplete',
    body: 'निकासी से पहले बैंक खाते का विवरण पूरा करें',
    locale: 'hi',
    sortOrder: 125,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.submitting',
    body: 'A withdrawal request is being submitted',
    locale: 'en',
    sortOrder: 126,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.submitting',
    body: 'निकासी अनुरोध जमा किया जा रहा है',
    locale: 'hi',
    sortOrder: 126,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_error',
    body: 'Minimum withdrawal amount is ₹100',
    locale: 'en',
    sortOrder: 127,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_error',
    body: 'न्यूनतम निकासी राशि ₹100 है',
    locale: 'hi',
    sortOrder: 127,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.max_error_template',
    body: 'Maximum available: {amount}',
    locale: 'en',
    sortOrder: 128,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.max_error_template',
    body: 'अधिकतम उपलब्ध: {amount}',
    locale: 'hi',
    sortOrder: 128,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_error',
    body: 'Select a complete bank account',
    locale: 'en',
    sortOrder: 129,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_error',
    body: 'पूरा बैंक खाता चुनें',
    locale: 'hi',
    sortOrder: 129,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_error',
    body: 'Enter a 6-digit PIN',
    locale: 'en',
    sortOrder: 130,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_error',
    body: '6 अंकों का पिन दर्ज करें',
    locale: 'hi',
    sortOrder: 130,
  },
];
