import { AppContentModule } from '../generated/prisma/enums';
import type { DefaultContent } from './app-content.defaults.types';

export const TRADING_DEFAULTS: DefaultContent[] = [
  // TRADING
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_title',
    body: 'No institutional offers available',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_title',
    body: 'कोई संस्थागत प्रस्ताव उपलब्ध नहीं',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_subtitle',
    body: 'Stocks will appear here when live market data is available.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_subtitle',
    body: 'लाइव बाज़ार डेटा उपलब्ध होने पर शेयर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_title',
    body: 'No OTC opportunities available',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_title',
    body: 'कोई ओटीसी अवसर उपलब्ध नहीं',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_subtitle',
    body: 'Backend-approved opportunities will appear here during the trading session.',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_subtitle',
    body: 'ट्रेडिंग सत्र में बैकएंड द्वारा स्वीकृत अवसर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.confirm_template',
    body: 'Submit IPO application {current} of {max}?\n\nPayment is automatic after allotment if your account has sufficient funds.',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.confirm_template',
    body: 'आईपीओ आवेदन {current}/{max} जमा करें?\n\nआवंटन के बाद यदि खाते में पर्याप्त राशि है तो भुगतान स्वचालित होगा।',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_title',
    body: 'No IPOs open for application',
    locale: 'en',
    sortOrder: 52,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_title',
    body: 'आवेदन के लिए कोई आईपीओ खुला नहीं',
    locale: 'hi',
    sortOrder: 52,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_subtitle',
    body: 'New IPO opportunities will appear here when applications open.',
    locale: 'en',
    sortOrder: 53,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_subtitle',
    body: 'आवेदन खुलने पर नए आईपीओ अवसर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 53,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_title',
    body: 'No IPO records',
    locale: 'en',
    sortOrder: 54,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_title',
    body: 'कोई आईपीओ रिकॉर्ड नहीं',
    locale: 'hi',
    sortOrder: 54,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_subtitle',
    body: 'Your IPO applications and available offers will appear here.',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_subtitle',
    body: 'आपके आईपीओ आवेदन और उपलब्ध प्रस्ताव यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_title',
    body: 'No investments yet',
    locale: 'en',
    sortOrder: 56,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_title',
    body: 'अभी कोई निवेश नहीं',
    locale: 'hi',
    sortOrder: 56,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_subtitle',
    body: 'No Institutional, OTC or IPO holdings yet.',
    locale: 'en',
    sortOrder: 57,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_subtitle',
    body: 'अभी कोई संस्थागत, ओटीसी या आईपीओ होल्डिंग नहीं है।',
    locale: 'hi',
    sortOrder: 57,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.explore_cta',
    body: 'Explore offers',
    locale: 'en',
    sortOrder: 58,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.explore_cta',
    body: 'प्रस्ताव देखें',
    locale: 'hi',
    sortOrder: 58,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_title',
    body: 'Portfolio',
    locale: 'en',
    sortOrder: 59,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_title',
    body: 'पोर्टफोलियो',
    locale: 'hi',
    sortOrder: 59,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_subtitle',
    body: 'Institutional · OTC · IPO',
    locale: 'en',
    sortOrder: 590,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_subtitle',
    body: 'Institutional · OTC · IPO',
    locale: 'hi',
    sortOrder: 590,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.loading',
    body: 'Loading portfolio',
    locale: 'en',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.loading',
    body: 'पोर्टफोलियो लोड हो रहा है',
    locale: 'hi',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.load_error_title',
    body: 'Unable to load portfolio',
    locale: 'en',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.load_error_title',
    body: 'पोर्टफोलियो लोड नहीं हो सका',
    locale: 'hi',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.stale_data',
    body: 'Showing previously loaded portfolio data.',
    locale: 'en',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.stale_data',
    body: 'पहले लोड किया गया पोर्टफोलियो डेटा दिखाया जा रहा है।',
    locale: 'hi',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.insufficient_history',
    body: 'Insufficient history',
    locale: 'en',
    sortOrder: 594,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.insufficient_history',
    body: 'पर्याप्त इतिहास उपलब्ध नहीं है',
    locale: 'hi',
    sortOrder: 594,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.no_activity',
    body: 'No product activity yet',
    locale: 'en',
    sortOrder: 595,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.no_activity',
    body: 'अभी कोई उत्पाद गतिविधि नहीं है',
    locale: 'hi',
    sortOrder: 595,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.day_return_note',
    body: "Day's return unavailable. This product summary does not include a daily P&L field.",
    locale: 'en',
    sortOrder: 653,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.day_return_note',
    body: 'आज का रिटर्न उपलब्ध नहीं है। इस उत्पाद सारांश में दैनिक P&L फ़ील्ड नहीं है।',
    locale: 'hi',
    sortOrder: 653,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.asset_details_heading',
    body: 'Asset Details',
    locale: 'en',
    sortOrder: 654,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.asset_details_heading',
    body: 'परिसंपत्ति विवरण',
    locale: 'hi',
    sortOrder: 654,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.holdings_heading',
    body: 'Holdings and Positions',
    locale: 'en',
    sortOrder: 655,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.holdings_heading',
    body: 'होल्डिंग्स और पोज़ीशन',
    locale: 'hi',
    sortOrder: 655,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.holdings_caption',
    body: 'Product holdings from the current portfolio response. Equity positions remain under Trade.',
    locale: 'en',
    sortOrder: 656,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.holdings_caption',
    body: 'वर्तमान पोर्टफोलियो प्रतिक्रिया से उत्पाद होल्डिंग्स। इक्विटी पोज़ीशन ट्रेड के अंतर्गत रहती हैं।',
    locale: 'hi',
    sortOrder: 656,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.performance_heading',
    body: 'Performance',
    locale: 'en',
    sortOrder: 657,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.performance_heading',
    body: 'प्रदर्शन',
    locale: 'hi',
    sortOrder: 657,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.no_holdings',
    body: 'No product holdings in the current response.',
    locale: 'en',
    sortOrder: 658,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.no_holdings',
    body: 'वर्तमान प्रतिक्रिया में कोई उत्पाद होल्डिंग नहीं है।',
    locale: 'hi',
    sortOrder: 658,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.related_fills_note',
    body: 'Related fills are not included in this product holding record.',
    locale: 'en',
    sortOrder: 659,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.related_fills_note',
    body: 'संबंधित फ़िल इस उत्पाद होल्डिंग रिकॉर्ड में शामिल नहीं हैं।',
    locale: 'hi',
    sortOrder: 659,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.performance_source_note',
    body: 'Source: recorded product snapshots. Returns cover recorded observations only. Deposits and ordinary stocks are excluded.',
    locale: 'en',
    sortOrder: 660,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.performance_source_note',
    body: 'स्रोत: रिकॉर्ड किए गए उत्पाद स्नैपशॉट। रिटर्न केवल रिकॉर्ड किए गए अवलोकनों को कवर करते हैं। जमा और साधारण शेयर शामिल नहीं हैं।',
    locale: 'hi',
    sortOrder: 660,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.recent_activity',
    body: 'Recent Activity',
    locale: 'en',
    sortOrder: 650,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.recent_activity',
    body: 'हाल की गतिविधि',
    locale: 'hi',
    sortOrder: 650,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.view_details',
    body: 'View Details',
    locale: 'en',
    sortOrder: 651,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.view_details',
    body: 'विवरण देखें',
    locale: 'hi',
    sortOrder: 651,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.close',
    body: 'Close',
    locale: 'en',
    sortOrder: 652,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.close',
    body: 'बंद करें',
    locale: 'hi',
    sortOrder: 652,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.value_label',
    body: 'Total Portfolio Value',
    locale: 'en',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.value_label',
    body: 'कुल पोर्टफोलियो मूल्य',
    locale: 'hi',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.summary_heading',
    body: 'Investment Summary',
    locale: 'en',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.summary_heading',
    body: 'निवेश सारांश',
    locale: 'hi',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.allocation_heading',
    body: 'Asset Allocation',
    locale: 'en',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.allocation_heading',
    body: 'परिसंपत्ति आवंटन',
    locale: 'hi',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.quantity',
    body: 'Quantity',
    locale: 'en',
    sortOrder: 594,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.available',
    body: 'Available',
    locale: 'en',
    sortOrder: 595,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.average_cost',
    body: 'Average cost',
    locale: 'en',
    sortOrder: 596,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_value',
    body: 'Current value',
    locale: 'en',
    sortOrder: 597,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.unrealized_pnl',
    body: 'Unrealized P&L',
    locale: 'en',
    sortOrder: 598,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.frozen',
    body: 'Frozen',
    locale: 'en',
    sortOrder: 599,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_price',
    body: 'Current price',
    locale: 'en',
    sortOrder: 600,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.invested',
    body: 'Invested',
    locale: 'en',
    sortOrder: 601,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.realized_pnl',
    body: 'Realized P&L',
    locale: 'en',
    sortOrder: 602,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.day_pnl',
    body: 'Day P&L',
    locale: 'en',
    sortOrder: 603,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_cost',
    body: 'Valued at cost. Market quote unavailable.',
    locale: 'en',
    sortOrder: 604,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_market',
    body: 'Valued from the current market quote in this response.',
    locale: 'en',
    sortOrder: 605,
  },
  {
    module: AppContentModule.TRADING,
    key: 'state.data_unavailable',
    body: 'Trading data is temporarily unavailable.',
    locale: 'en',
    sortOrder: 606,
  },
  {
    module: AppContentModule.TRADING,
    key: 'state.loading',
    body: 'Loading trading data',
    locale: 'en',
    sortOrder: 606.5,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.clear_filters',
    body: 'Clear filters',
    locale: 'en',
    sortOrder: 607,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_title',
    body: 'No matching orders',
    locale: 'en',
    sortOrder: 608,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_message',
    body: 'Nothing in the currently loaded orders matches these filters.',
    locale: 'en',
    sortOrder: 609,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.buy',
    body: 'Buy',
    locale: 'en',
    sortOrder: 610,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.sell',
    body: 'Sell',
    locale: 'en',
    sortOrder: 611,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.retry',
    body: 'Retry',
    locale: 'en',
    sortOrder: 612,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.quantity',
    body: 'मात्रा',
    locale: 'hi',
    sortOrder: 594,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.available',
    body: 'उपलब्ध',
    locale: 'hi',
    sortOrder: 595,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.average_cost',
    body: 'औसत लागत',
    locale: 'hi',
    sortOrder: 596,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_value',
    body: 'वर्तमान मूल्य',
    locale: 'hi',
    sortOrder: 597,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.unrealized_pnl',
    body: 'अवास्तविक लाभ/हानि',
    locale: 'hi',
    sortOrder: 598,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.frozen',
    body: 'फ्रीज़ की गई',
    locale: 'hi',
    sortOrder: 599,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_price',
    body: 'वर्तमान कीमत',
    locale: 'hi',
    sortOrder: 600,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.invested',
    body: 'निवेशित',
    locale: 'hi',
    sortOrder: 601,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.realized_pnl',
    body: 'वास्तविक लाभ/हानि',
    locale: 'hi',
    sortOrder: 602,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.day_pnl',
    body: 'आज का लाभ/हानि',
    locale: 'hi',
    sortOrder: 603,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_cost',
    body: 'लागत पर मूल्यांकन। बाजार भाव उपलब्ध नहीं है।',
    locale: 'hi',
    sortOrder: 604,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_market',
    body: 'इस प्रतिक्रिया में वर्तमान बाजार भाव के आधार पर मूल्यांकन किया गया है।',
    locale: 'hi',
    sortOrder: 605,
  },
  {
    module: AppContentModule.TRADING,
    key: 'state.data_unavailable',
    body: 'ट्रेडिंग डेटा अस्थायी रूप से उपलब्ध नहीं है।',
    locale: 'hi',
    sortOrder: 606,
  },
  {
    module: AppContentModule.TRADING,
    key: 'state.loading',
    body: 'ट्रेडिंग डेटा लोड हो रहा है',
    locale: 'hi',
    sortOrder: 606.5,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.clear_filters',
    body: 'फ़िल्टर साफ़ करें',
    locale: 'hi',
    sortOrder: 607,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_title',
    body: 'कोई मेल खाता ऑर्डर नहीं',
    locale: 'hi',
    sortOrder: 608,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_message',
    body: 'वर्तमान में लोड किए गए किसी ऑर्डर से ये फ़िल्टर मेल नहीं खाते।',
    locale: 'hi',
    sortOrder: 609,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.buy',
    body: 'खरीदें',
    locale: 'hi',
    sortOrder: 610,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.sell',
    body: 'बेचें',
    locale: 'hi',
    sortOrder: 611,
  },
  {
    module: AppContentModule.TRADING,
    key: 'action.retry',
    body: 'पुनः प्रयास करें',
    locale: 'hi',
    sortOrder: 612,
  },

  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_title',
    body: 'No holdings',
    locale: 'en',
    sortOrder: 85,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_title',
    body: 'कोई होल्डिंग नहीं है',
    locale: 'hi',
    sortOrder: 85,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_subtitle',
    body: 'Your holdings will appear here after settled positions are added.',
    locale: 'en',
    sortOrder: 86,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_subtitle',
    body: 'निपटान के बाद होल्डिंग यहाँ दिखेंगी।',
    locale: 'hi',
    sortOrder: 86,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.trades',
    body: 'Trades',
    locale: 'en',
    sortOrder: 610,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.trades',
    body: 'ट्रेड्स',
    locale: 'hi',
    sortOrder: 610,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.institutional',
    body: 'Institutional',
    locale: 'en',
    sortOrder: 611,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.institutional',
    body: 'संस्थागत',
    locale: 'hi',
    sortOrder: 611,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.holdings',
    // Stable legacy key retained for compatibility — display label is Positions.
    body: 'Positions',
    locale: 'en',
    sortOrder: 612,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.holdings',
    body: 'पोजीशन',
    locale: 'hi',
    sortOrder: 612,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.pending',
    body: 'Pending',
    locale: 'en',
    sortOrder: 613,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.pending',
    body: 'लंबित',
    locale: 'hi',
    sortOrder: 613,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.order_book',
    body: 'Order Book',
    locale: 'en',
    sortOrder: 614,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.order_book',
    body: 'ऑर्डर बुक',
    locale: 'hi',
    sortOrder: 614,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.otc',
    body: 'OTC',
    locale: 'en',
    sortOrder: 615,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.otc',
    body: 'ओटीसी',
    locale: 'hi',
    sortOrder: 615,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.ipo',
    body: 'IPO',
    locale: 'en',
    sortOrder: 616,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.ipo',
    body: 'आईपीओ',
    locale: 'hi',
    sortOrder: 616,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.history',
    body: 'History',
    locale: 'en',
    sortOrder: 617,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.history',
    body: 'इतिहास',
    locale: 'hi',
    sortOrder: 617,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.funds_ledger',
    body: 'Funds Ledger',
    locale: 'en',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.funds_ledger',
    body: 'राशि लेजर',
    locale: 'hi',
    sortOrder: 618,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.all',
    // Stable legacy key retained for compatibility — display label is Overview.
    body: 'Overview',
    locale: 'en',
    sortOrder: 619,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.all',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 619,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.ins_stock',
    body: 'Ins. Stock',
    locale: 'en',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.ins_stock',
    body: 'संस्थागत शेयर',
    locale: 'hi',
    sortOrder: 620,
  },

  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'Overview',
    locale: 'en',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'Overview',
    locale: 'en',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.orders',
    body: 'Orders',
    locale: 'en',
    sortOrder: 621,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.orders',
    body: 'ऑर्डर',
    locale: 'hi',
    sortOrder: 621,
  },

  {
    module: AppContentModule.TRADING,
    key: 'guide.institutional',
    title: 'Institutional offers',
    body: 'Institutional stocks settle at the live market price. Review eligibility and terms before trading.',
    locale: 'en',
    sortOrder: 60,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.institutional',
    title: 'संस्थागत प्रस्ताव',
    body: 'संस्थागत शेयर लाइव बाज़ार कीमत पर निपटाए जाते हैं। ट्रेड से पहले पात्रता और शर्तें देखें।',
    locale: 'hi',
    sortOrder: 60,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.otc',
    title: 'OTC trading',
    body: 'The market quote is for reference only. Purchases settle at the discount settlement price shown in the trade dialog. Enter quantity and the 4-digit transaction key; orders stay Pending Review until approved and appear in holdings only after approval.',
    locale: 'en',
    sortOrder: 70,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.otc',
    title: 'ओटीसी ट्रेडिंग',
    body: 'बाज़ार भाव केवल संदर्भ के लिए है। खरीद ट्रेड डायलॉग में दिखाए गए डिस्काउंट निपटान मूल्य पर होती है। मात्रा और 4 अंकों की लेनदेन कुंजी दर्ज करें; स्वीकृति तक समीक्षा लंबित रहती है और उसके बाद ही होल्डिंग में दिखती है।',
    locale: 'hi',
    sortOrder: 70,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.ipo',
    title: 'IPO applications',
    body: 'IPO applications may be pending, allocated or rejected. An allocation can create an outstanding payment obligation. Check notices before assuming shares are sellable.',
    locale: 'en',
    sortOrder: 80,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.ipo',
    title: 'आईपीओ आवेदन',
    body: 'आईपीओ आवेदन लंबित, आवंटित या अस्वीकृत हो सकता है। आवंटन पर भुगतान बकाया हो सकता है। शेयर बेचने योग्य मानने से पहले सूचनाएँ जाँचें।',
    locale: 'hi',
    sortOrder: 80,
  },
];
