import { AppContentModule } from '../generated/prisma/enums';

type DefaultContent = {
  module: AppContentModule;
  key: string;
  title?: string | null;
  body: string;
  locale?: string;
  sortOrder?: number;
  isActive?: boolean;
};

const privacyDocument = {
  effective: 'Effective 13 August 2026  •  Version 1.0',
  sections: [
    {
      heading: '1. Who we are',
      body: 'This policy explains how the operator of the India Trading application (India Trading, we, us or our) processes personal data when you register for, access or use the application, website, customer support and related services. The operator’s final legal name, registered address and grievance contact must be displayed in About Us before public release.',
    },
    {
      heading: '2. Data we collect',
      body: 'We may collect your name, Indian mobile number, email address, date of birth, address, tax and KYC identifiers and documents, profile image, bank-account details, account balances, orders, transactions, holdings and settlement records. We also collect device, IP address, login and security logs, notification preferences, customer-support messages and files you choose to send. If you link Google, we receive the verified email and account identifier needed for sign-in.',
    },
    {
      heading: '3. Biometrics',
      body: 'Face ID or fingerprint verification is performed by your device operating system. India Trading does not receive or store your biometric template. When you enable quick login, the application stores a revocable, time-limited login credential in device storage. Resetting your password invalidates that credential and you must enable quick login again.',
    },
    {
      heading: '4. Why we use data',
      body: 'We use personal data to create and protect accounts; authenticate users; complete KYC and other required checks; provide market information; accept, review, process and settle transactions under the applicable product workflow; maintain bank-account records; send OTPs and service notifications; provide support; investigate fraud, abuse and security incidents; maintain audit records; improve reliability; and comply with lawful obligations.',
    },
    {
      heading: '5. Consent and required processing',
      body: 'We request consent where required and provide a way to withdraw it. Withdrawal does not affect processing already completed and may prevent us from providing functions that require the withdrawn data. Some information remains necessary to perform your requested service, secure the platform, resolve disputes or meet legal and record-keeping duties.',
    },
    {
      heading: '6. Who receives data',
      body: 'We may share only the information reasonably necessary with cloud and security providers, SMS/OTP providers, Google authentication, market-data providers, banks and settlement service providers, the business or support team assigned to your account, professional advisers, and competent government, regulatory or law-enforcement authorities. We do not sell personal data for money.',
    },
    {
      heading: '7. Storage, transfer and retention',
      body: 'Data may be processed in India and in other locations used by our contracted providers, subject to applicable transfer restrictions. We retain data only for the service, security, dispute-resolution and legal periods that apply. Security and system logs are retained for at least the period required by applicable Indian cyber-security directions. Data is deleted or anonymised when it is no longer required, unless preservation is legally required.',
    },
    {
      heading: '8. Security',
      body: 'We use access controls, encrypted transport, password hashing, expiring OTPs, authentication controls, audit logging and operational safeguards appropriate to the nature of the data. No system can guarantee absolute security. Keep your password, OTP and transaction key confidential and notify Online Customer Service immediately if you suspect unauthorised access.',
    },
    {
      heading: '9. Your choices and rights',
      body: 'Subject to applicable law, you may request information about processing, access the information made available to you, correct inaccurate or incomplete data, request erasure where retention is not required, withdraw consent, nominate another person to exercise applicable rights, and raise a grievance. You can update available profile fields or contact Online Customer Service in the application. We may verify identity before completing a request.',
    },
    {
      heading: '10. Children',
      body: 'The service is intended only for persons aged 18 or older. Do not register or provide personal data if you are under 18.',
    },
    {
      heading: '11. Updates and contact',
      body: 'We may update this policy and will show the new effective date and provide any notice required by law. For privacy questions, rights requests or grievances, use Online Customer Service in the application. The operator must publish the designated grievance contact and formal service address in About Us before launch.',
    },
  ],
};

const termsDocument = {
  effective: 'Effective 13 August 2026  •  Version 1.0',
  sections: [
    {
      heading: '1. Agreement and eligibility',
      body: 'These Terms govern your use of India Trading. By creating an account or using the service, you agree to them and the Privacy Policy. You must be at least 18, legally capable of contracting, provide accurate information, complete required verification and use the service only for yourself unless the operator expressly authorises another arrangement.',
    },
    {
      heading: '2. Account security',
      body: 'You are responsible for protecting your password, OTP, transaction key and registered device. Google and biometric quick login are optional. Device biometrics only unlock a stored quick-login credential; they do not replace transaction authorisation where a transaction key or another confirmation is required. Report suspected unauthorised access immediately.',
    },
    {
      heading: '3. Services and product workflows',
      body: 'The application provides market information and product-specific transaction workflows. Ordinary-stock orders follow the market hours, price, order-state and settlement rules disclosed in the application. Institutional offers, IPOs and OTC products are available only through Trading and use their separately displayed eligibility, pricing, allocation, review and settlement rules. OTC purchases require quantity and transaction-key confirmation, remain Pending Review until approved by the backend, and appear in the relevant completed position only after approval. Institutional and OTC products have no minimum quantity unless a specific product disclosure states otherwise.',
    },
    {
      heading: '4. Execution and settlement disclosure',
      body: 'The application does not itself connect an order directly to a securities exchange. Transactions are processed and settled through the operator’s disclosed backend arrangements. A displayed real-time or reference price does not by itself prove exchange execution. Before accepting transactions, the operator must clearly identify the contracting entity, execution or allocation model, custody or ownership record, settlement timing, cancellation rules and user recourse for each product.',
    },
    {
      heading: '5. Orders and authorisation',
      body: 'Review the instrument, side, quantity, price basis, charges and total before confirming. Submitting an instruction authorises the applicable workflow but does not guarantee acceptance, execution, allocation or approval. Instructions may be rejected or remain pending because of account status, market hours, price availability, insufficient balance, risk controls, product availability, compliance review, technical interruption or other disclosed rules. Completed or settled instructions may not be reversible.',
    },
    {
      heading: '6. Market data and risk',
      body: 'Prices, charts, news and indicators are provided for information and may be delayed, unavailable, corrected or differ from a final transaction or settlement price. Investments can lose value, allocation may be unavailable and past performance is not a guarantee. India Trading does not guarantee profits or uninterrupted access. Nothing in the application is personal investment, tax or legal advice unless expressly identified as such by an authorised professional.',
    },
    {
      heading: '7. Money, bank accounts, charges and taxes',
      body: 'Add Funds opens Online Customer Service; it is not an automatic deposit or payment confirmation. Follow only verified in-app instructions and confirm that funds are credited to your account record. A bank account you add is recorded in the backend without a separate approval step, but ownership or compliance checks may still be required before withdrawal or settlement. Applicable prices, fees, taxes, deductions and settlement amounts must be shown or otherwise disclosed before they are charged.',
    },
    {
      heading: '8. Prohibited use',
      body: 'You must not impersonate another person, provide false KYC or bank data, share or misuse credentials, manipulate transactions or prices, exploit errors, interfere with security, introduce malicious code, use unlawful funds, evade applicable restrictions, scrape protected services or use the platform for fraud, market abuse or any illegal purpose.',
    },
    {
      heading: '9. Suspension and termination',
      body: 'We may restrict or suspend access when reasonably necessary for security, suspected fraud, incomplete verification, legal compliance, misuse, material breach, system protection or a valid authority request. Where permitted, we will provide notice and a route to contact support. Termination does not remove accrued payment, settlement, record-keeping or dispute obligations.',
    },
    {
      heading: '10. Availability and liability',
      body: 'We use reasonable care to operate the service but availability can be affected by networks, devices, data providers, banking systems and events outside our control. To the maximum extent permitted by law, the operator is not liable for indirect or consequential loss. Nothing in these Terms excludes liability or consumer rights that cannot lawfully be excluded. Product-specific disclosures prevail if they provide greater protection.',
    },
    {
      heading: '11. Changes, complaints and governing terms',
      body: 'We may change these Terms prospectively and will show the effective date and provide required notice. Raise service or transaction complaints through Online Customer Service and keep the ticket reference. Before public release, the operator must insert its legal entity name, registered address, grievance officer, applicable licence or registration details (only if actually held), governing law, courts or arbitration venue, and escalation channels in About Us and the final version of these Terms.',
    },
  ],
};

const riskDocument = {
  effective: 'Effective 16 September 2026  •  Version 1.0',
  sections: [
    { heading: '1. Capital and market risk', body: 'Investments can rise or fall in value and you may lose some or all of the capital committed. Market prices can change rapidly because of issuer, sector, economic, political, currency or broader market events. Past performance and displayed returns do not guarantee future results.' },
    { heading: '2. Volatility and liquidity risk', body: 'Some instruments may experience sharp price movements or limited trading interest. You may be unable to buy or sell the desired quantity at the displayed price, or at all. Low liquidity can increase price impact and the time required to complete or settle a transaction.' },
    { heading: '3. Execution and price risk', body: 'Quotes, charts and reference prices may be delayed, corrected or differ from the final transaction or settlement price. Submitting an instruction does not guarantee acceptance, execution, allocation or approval. Review the instrument, quantity, price basis, charges and total before confirming.' },
    { heading: '4. Product-specific risk', body: 'Institutional offers, IPOs and OTC products may involve restricted eligibility, uncertain allocation, limited liquidity, valuation uncertainty and additional review or settlement steps. OTC transactions remain pending until approved. Read the product details and do not treat an application or displayed position as a completed allocation or settlement.' },
    { heading: '5. Settlement, custody and counterparty risk', body: 'Transactions depend on the disclosed operator, banking, custody, allocation and settlement arrangements. Delays, rejection, reconciliation issues or counterparty failure may affect when cash or assets become available. Confirm the contracting entity, ownership record, settlement timing, cancellation rules and complaint route before transacting.' },
    { heading: '6. System and data risk', body: 'The application, networks, devices, market-data services, banking systems or other providers may be unavailable or contain delayed or inaccurate information. A pending screen, notification or balance display is not conclusive proof of execution or settlement. Check transaction records and contact support when information conflicts.' },
    { heading: '7. Borrowing and leverage risk', body: 'Borrowing money or using leverage to invest can magnify losses and may create repayment obligations even when an investment loses value. Do not borrow or commit funds needed for essential expenses, emergencies or near-term obligations.' },
    { heading: '8. Fraud and account-security risk', body: 'Fraudsters may impersonate staff or promise guaranteed returns. Never share passwords, OTPs or transaction keys, and use only verified in-app support channels. Report unauthorised activity promptly. India Trading does not guarantee returns or ask you to bypass the displayed transaction workflow.' },
    { heading: '9. Regulatory and tax risk', body: 'Laws, regulatory requirements, taxes, fees and product availability may change and can affect transactions or returns. Your tax and legal position depends on your circumstances. Obtain independent professional advice where needed.' },
    { heading: '10. Make an informed decision', body: 'This application provides information and transaction workflows; it does not provide personal investment, legal or tax advice unless expressly identified as such by an authorised professional. Consider your objectives, financial position, time horizon and ability to bear loss. Read all product disclosures and seek independent advice before acting if you do not understand the risks.' },
  ],
};

const insightArticles: Array<{
  key: string;
  titleEn: string;
  bodyEn: string;
  titleHi: string;
  bodyHi: string;
  sortOrder: number;
}> = [
  {
    key: 'article.01',
    titleEn: 'Account and KYC',
    bodyEn:
      'Register with your phone number and invitation code. Keep your login password private. Your account ID is read-only; your name can be updated in Personal Information.\n\nSubmit clear, complete Aadhaar or PAN documents through KYC Verification. Check the review status before adding a bank account. If documents are rejected, review the reason and upload corrected documents. Do not send identity documents through unsolicited messages.',
    titleHi: 'खाता और केवाईसी',
    bodyHi:
      'अपने मोबाइल नंबर और आमंत्रण कोड से पंजीकरण करें। लॉगिन पासवर्ड गोपनीय रखें। खाता आईडी बदली नहीं जा सकती; व्यक्तिगत जानकारी में नाम बदला जा सकता है।\n\nकेवाईसी सत्यापन में स्पष्ट और पूर्ण आधार या पैन दस्तावेज़ जमा करें। बैंक खाता जोड़ने से पहले समीक्षा की स्थिति देखें। अस्वीकृति पर कारण पढ़ें और सही दस्तावेज़ जमा करें। अनचाहे संदेशों में पहचान दस्तावेज़ न भेजें।',
    sortOrder: 10,
  },
  {
    key: 'article.02',
    titleEn: 'Market basics',
    bodyEn:
      'A quote is the latest available price, not a promise of execution. Quotes may be delayed or unavailable. Check the exchange, trading session and quote timestamp before placing an order.\n\nA watchlist tracks instruments; adding a symbol does not buy it. Price charts show historical market observations. They do not predict future returns.',
    titleHi: 'बाज़ार की मूल बातें',
    bodyHi:
      'भाव नवीनतम उपलब्ध कीमत है, निष्पादन की गारंटी नहीं। भाव में देरी हो सकती है या वह उपलब्ध नहीं हो सकता। ऑर्डर देने से पहले एक्सचेंज, सत्र और भाव का समय देखें।\n\nवॉचलिस्ट केवल शेयरों पर नज़र रखती है; शेयर जोड़ने से खरीद नहीं होती। चार्ट पिछले बाज़ार भाव दिखाते हैं, भविष्य के रिटर्न का अनुमान नहीं।',
    sortOrder: 20,
  },
  {
    key: 'article.03',
    titleEn: 'Order types',
    bodyEn:
      'A market order requests execution at the available price. The final price can differ from the quote, especially when liquidity is low or prices move quickly.\n\nA limit order sets the highest purchase price or lowest sale price you accept. It may fill partly or not at all. Review quantity, price, available funds and order status. An order submission is not a completed trade; check fills in Order Book and Order History.',
    titleHi: 'ऑर्डर प्रकार',
    bodyHi:
      'मार्केट ऑर्डर उपलब्ध भाव पर निष्पादन का अनुरोध करता है। कम तरलता या तेज़ बदलाव में अंतिम कीमत दिखाए गए भाव से अलग हो सकती है।\n\nलिमिट ऑर्डर खरीद की अधिकतम या बिक्री की न्यूनतम स्वीकार्य कीमत तय करता है। वह आंशिक रूप से पूरा हो सकता है या नहीं भी। मात्रा, कीमत, उपलब्ध राशि और स्थिति जाँचें। ऑर्डर भेजना पूरा हुआ ट्रेड नहीं है; ऑर्डर बुक और इतिहास में निष्पादन देखें।',
    sortOrder: 30,
  },
  {
    key: 'article.04',
    titleEn: 'Order validity',
    bodyEn:
      'DAY orders remain eligible during the trading day and expire if not filled by the session cutoff. IOC means immediate-or-cancel: any unfilled remainder is cancelled. FOK means fill-or-kill: the entire quantity must execute immediately or the order is cancelled.\n\nOnly use validity options supported by the selected order screen. A cancellation request may race with a fill. Refresh the order status and holdings before submitting a replacement.',
    titleHi: 'ऑर्डर वैधता',
    bodyHi:
      'DAY ऑर्डर ट्रेडिंग दिन तक मान्य रहता है और सत्र समाप्त होने पर अधूरा हिस्सा समाप्त हो जाता है। IOC में तुरंत पूरा न हुआ हिस्सा रद्द होता है। FOK में पूरी मात्रा तुरंत पूरी होनी चाहिए, अन्यथा ऑर्डर रद्द होता है।\n\nकेवल ऑर्डर स्क्रीन पर उपलब्ध अवधि विकल्प चुनें। रद्द करने के दौरान भी निष्पादन हो सकता है। नया ऑर्डर देने से पहले स्थिति और होल्डिंग रीफ़्रेश करें।',
    sortOrder: 40,
  },
  {
    key: 'article.05',
    titleEn: 'Funding and withdrawals',
    bodyEn:
      'Use Add Funds to contact the in-app support team. Funds appear only after the finance team confirms and credits the account. Check the Funds Ledger for completed entries.\n\nSet a six-digit Withdrawal PIN in Profile. This is separate from your login password and is required when submitting a withdrawal. Add an approved bank account and check available funds. The minimum withdrawal is INR 100. Submitted funds are frozen during review; approval debits cash, while rejection releases the frozen amount. Keep the withdrawal order number for follow-up.',
    titleHi: 'जमा और निकासी',
    bodyHi:
      'राशि जोड़ने के लिए ऐप की सहायता टीम से संपर्क करें। वित्त टीम की पुष्टि और क्रेडिट के बाद ही राशि दिखाई देती है। पूरे हुए लेनदेन राशि के लेजर में देखें।\n\nप्रोफ़ाइल में छह अंकों का निकासी पिन सेट करें। यह लॉगिन पासवर्ड से अलग है और निकासी अनुरोध के लिए आवश्यक है। स्वीकृत बैंक खाता जोड़ें और उपलब्ध राशि जाँचें। न्यूनतम निकासी 100 रुपये है। समीक्षा के दौरान राशि रोक दी जाती है; स्वीकृति पर कटती है और अस्वीकृति पर मुक्त होती है। अनुरोध का ऑर्डर नंबर सुरक्षित रखें।',
    sortOrder: 50,
  },
  {
    key: 'article.06',
    titleEn: 'Holdings and returns',
    bodyEn:
      'Home Total Asset Value combines account cash and all stock holdings. Available funds and frozen margin are parts of account funds, not additional assets. Portfolio is limited to Institutional, OTC and IPO holdings; ordinary stocks remain in trading holdings.\n\nUnrealized profit or loss compares current valuation with acquisition cost. Realized profit or loss comes from completed sales. Period returns use recorded account profit observations, not deposits. History begins when reliable observations are available; insufficient history is shown explicitly. Missing quotes may use cost as a fallback valuation.',
    titleHi: 'होल्डिंग और रिटर्न',
    bodyHi:
      'होम पर कुल परिसंपत्ति मूल्य में खाते की नकदी और सभी शेयर होल्डिंग शामिल हैं। उपलब्ध राशि और रोका गया मार्जिन खाते की राशि के हिस्से हैं, अतिरिक्त परिसंपत्तियाँ नहीं। पोर्टफोलियो में केवल संस्थागत, ओटीसी और आईपीओ हैं; सामान्य शेयर ट्रेडिंग होल्डिंग में रहते हैं।\n\nअप्राप्त लाभ या हानि वर्तमान मूल्य और खरीद लागत का अंतर है। प्राप्त लाभ या हानि पूरी हुई बिक्री से आती है। अवधि का रिटर्न दर्ज किए गए लाभ के अवलोकनों पर आधारित है, जमा राशि पर नहीं। पर्याप्त विश्वसनीय इतिहास न होने पर यह स्पष्ट दिखाया जाता है। भाव न मिलने पर लागत को वैकल्पिक मूल्य माना जा सकता है।',
    sortOrder: 60,
  },
  {
    key: 'article.07',
    titleEn: 'Institutional, OTC and IPO',
    bodyEn:
      'Review each offer’s price, eligibility and terms before submitting. Institutional offers and OTC orders can require review. An application or pending order is not a settled holding.\n\nIPO applications may be pending, allocated or rejected. An allocation can create an outstanding payment obligation. Check the allocation notice, required payment and status before assuming shares are available to sell. Portfolio allocation includes settled positions, not pending applications. Availability and returns are never guaranteed.',
    titleHi: 'संस्थागत, ओटीसी और आईपीओ',
    bodyHi:
      'आवेदन से पहले हर प्रस्ताव की कीमत, पात्रता और शर्तें पढ़ें। संस्थागत प्रस्ताव और ओटीसी ऑर्डर की समीक्षा आवश्यक हो सकती है। आवेदन या लंबित ऑर्डर निपटान की गई होल्डिंग नहीं है।\n\nआईपीओ आवेदन लंबित, आवंटित या अस्वीकृत हो सकता है। आवंटन पर भुगतान बकाया हो सकता है। शेयर बेचने योग्य मानने से पहले आवंटन सूचना, भुगतान और स्थिति जाँचें। परिसंपत्ति आवंटन में निपटान की गई होल्डिंग आती है, लंबित आवेदन नहीं। उपलब्धता और रिटर्न की गारंटी नहीं है।',
    sortOrder: 70,
  },
  {
    key: 'article.08',
    titleEn: 'Risk and account security',
    bodyEn:
      'Investments can lose value. Concentration, liquidity, price gaps and operational delays can increase losses. Borrowed funds add repayment obligations. Read product terms and do not rely on past performance as a guarantee.\n\nNever share passwords or your Withdrawal PIN, including with someone claiming to be support. Change your login password from Change Password and your withdrawal password from Transaction PIN. Five failed PIN attempts temporarily lock PIN verification. If you suspect account misuse, contact in-app support promptly. This learning material is general education, not personalized investment advice.',
    titleHi: 'जोखिम और खाता सुरक्षा',
    bodyHi:
      'निवेश का मूल्य घट सकता है। एक ही निवेश में अधिक राशि, कम तरलता, कीमत में अंतर और परिचालन देरी से नुकसान बढ़ सकता है। उधार की राशि चुकाने की ज़िम्मेदारी होती है। उत्पाद की शर्तें पढ़ें और पिछले प्रदर्शन को गारंटी न मानें।\n\nपासवर्ड या निकासी पिन किसी से साझा न करें, सहायता कर्मचारी होने का दावा करने वाले से भी नहीं। लॉगिन पासवर्ड और निकासी पिन अलग पृष्ठों से बदलें। पाँच गलत पिन प्रयासों के बाद सत्यापन अस्थायी रूप से बंद हो जाता है। दुरुपयोग की आशंका पर ऐप सहायता से संपर्क करें। यह सामान्य शिक्षा है, व्यक्तिगत निवेश सलाह नहीं।',
    sortOrder: 80,
  },
];

export const APP_CONTENT_DEFAULTS: DefaultContent[] = [
  // HOME
  { module: AppContentModule.HOME, key: 'notifications.title', body: 'Notifications', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.title', body: 'सूचनाएँ', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.loading', body: 'Loading notifications', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.loading', body: 'सूचनाएँ लोड हो रही हैं', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.load_error', body: 'Unable to load notifications', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.load_error', body: 'सूचनाएँ लोड नहीं हो सकीं', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.load_error_body', body: 'The server did not return notifications. You can retry.', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.load_error_body', body: 'सर्वर से सूचनाएँ नहीं मिलीं। आप फिर प्रयास कर सकते हैं।', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.empty_title', body: 'No notifications yet', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.empty_title', body: 'अभी कोई सूचना नहीं है', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.empty_body', body: 'Account and order updates will appear here when the server sends them.', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.empty_body', body: 'खाता और ऑर्डर अपडेट मिलने पर वे यहाँ दिखाई देंगे।', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.recent', body: 'Recent updates', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.recent', body: 'हाल के अपडेट', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.caught_up', body: 'All caught up', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.caught_up', body: 'सभी सूचनाएँ पढ़ ली गई हैं', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.unread_count', body: '{count} unread', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.unread_count', body: '{count} अपठित', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.mark_read_error', body: 'Unable to mark notification as read', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.mark_read_error', body: 'सूचना को पढ़ा हुआ चिह्नित नहीं किया जा सका', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.mark_all_error', body: 'Unable to mark all notifications', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.mark_all_error', body: 'सभी सूचनाओं को पढ़ा हुआ चिह्नित नहीं किया जा सका', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.marking', body: 'Marking notifications as read', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.marking', body: 'सूचनाओं को पढ़ा हुआ चिह्नित किया जा रहा है', locale: 'hi', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.unread', body: 'Unread', locale: 'en', sortOrder: 5 },
  { module: AppContentModule.HOME, key: 'notifications.unread', body: 'अपठित', locale: 'hi', sortOrder: 5 },
  {
    module: AppContentModule.HOME,
    key: 'banner.title',
    body: 'Track live markets & place orders on the go',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.title',
    body: 'लाइव बाज़ार ट्रैक करें और कहीं से भी ऑर्डर दें',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.subtitle',
    body: 'Explore equities, institutional offers, OTC and IPOs',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.HOME,
    key: 'banner.subtitle',
    body: 'इक्विटी, संस्थागत प्रस्ताव, ओटीसी और आईपीओ देखें',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.title',
    body: 'Track live markets & place orders on the go',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.title',
    body: 'लाइव बाज़ार ट्रैक करें और कहीं से भी ऑर्डर दें',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.subtitle',
    body: 'Live prices, company logos and secure execution',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.HOME,
    key: 'markets.banner.subtitle',
    body: 'लाइव कीमतें, कंपनी लोगो और सुरक्षित निष्पादन',
    locale: 'hi',
    sortOrder: 40,
  },
  { module: AppContentModule.HOME, key: 'markets.loading', body: 'Loading markets…', locale: 'en', sortOrder: 40 },
  { module: AppContentModule.HOME, key: 'markets.loading', body: 'बाज़ार लोड हो रहे हैं…', locale: 'hi', sortOrder: 40 },
  { module: AppContentModule.HOME, key: 'markets.watchlist_error_title', body: 'Unable to load watchlist', locale: 'en', sortOrder: 41 },
  { module: AppContentModule.HOME, key: 'markets.watchlist_error_title', body: 'वॉचलिस्ट लोड नहीं हो सकी', locale: 'hi', sortOrder: 41 },
  { module: AppContentModule.HOME, key: 'markets.watchlist_error_body', body: 'Watchlist data is unavailable. Please try again.', locale: 'en', sortOrder: 42 },
  { module: AppContentModule.HOME, key: 'markets.watchlist_error_body', body: 'वॉचलिस्ट डेटा उपलब्ध नहीं है। कृपया फिर प्रयास करें।', locale: 'hi', sortOrder: 42 },
  { module: AppContentModule.HOME, key: 'markets.search_error_title', body: 'Market data unavailable', locale: 'en', sortOrder: 43 },
  { module: AppContentModule.HOME, key: 'markets.search_error_title', body: 'बाज़ार डेटा उपलब्ध नहीं है', locale: 'hi', sortOrder: 43 },
  { module: AppContentModule.HOME, key: 'markets.search_error_body', body: 'Network error or live search is unavailable. Please refresh to try again.', locale: 'en', sortOrder: 44 },
  { module: AppContentModule.HOME, key: 'markets.search_error_body', body: 'नेटवर्क में समस्या है या लाइव खोज उपलब्ध नहीं है। कृपया रीफ़्रेश करके फिर प्रयास करें।', locale: 'hi', sortOrder: 44 },
  { module: AppContentModule.HOME, key: 'markets.load_more', body: 'Load more', locale: 'en', sortOrder: 45 },
  { module: AppContentModule.HOME, key: 'markets.load_more', body: 'और देखें', locale: 'hi', sortOrder: 45 },
  { module: AppContentModule.HOME, key: 'markets.load_more_retry', body: 'Unable to load stocks. Retry', locale: 'en', sortOrder: 46 },
  { module: AppContentModule.HOME, key: 'markets.load_more_retry', body: 'स्टॉक लोड नहीं हो सके। फिर प्रयास करें', locale: 'hi', sortOrder: 46 },
  { module: AppContentModule.HOME, key: 'markets.refresh', body: 'Refresh market data', locale: 'en', sortOrder: 47 },
  { module: AppContentModule.HOME, key: 'markets.refresh', body: 'बाज़ार डेटा रीफ़्रेश करें', locale: 'hi', sortOrder: 47 },
  { module: AppContentModule.HOME, key: 'markets.search_page.title', body: 'Search stocks', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.title', body: 'स्टॉक खोजें', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.hint', body: 'Search symbol or company', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.hint', body: 'प्रतीक या कंपनी खोजें', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.searching', body: 'Searching stocks…', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.searching', body: 'स्टॉक खोजे जा रहे हैं…', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.watchlist_update_error', body: 'Unable to update watchlist', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.watchlist_update_error', body: 'वॉचलिस्ट अपडेट नहीं हो सकी', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.partial_error', body: 'Live search is unavailable. Showing loaded instruments.', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.partial_error', body: 'लाइव खोज उपलब्ध नहीं है। पहले से लोड किए गए साधन दिखाए जा रहे हैं।', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.more_error', body: 'More results could not be loaded. Your current results are still available.', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.more_error', body: 'और परिणाम लोड नहीं हो सके। मौजूदा परिणाम अभी भी उपलब्ध हैं।', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.error_title', body: 'Unable to load stocks', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.error_title', body: 'स्टॉक लोड नहीं हो सके', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.error_body', body: 'Search is temporarily unavailable. Please retry.', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.error_body', body: 'खोज अस्थायी रूप से उपलब्ध नहीं है। कृपया फिर प्रयास करें।', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.empty_title', body: 'No instruments available', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.empty_title', body: 'कोई साधन उपलब्ध नहीं है', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.empty_body', body: 'Try again when market data is available.', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.empty_body', body: 'बाज़ार डेटा उपलब्ध होने पर फिर प्रयास करें।', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.no_match_title', body: 'No matching stocks', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.no_match_title', body: 'कोई मिलता-जुलता स्टॉक नहीं मिला', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.no_match_body', body: 'Try a different symbol or company name.', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.no_match_body', body: 'कोई दूसरा प्रतीक या कंपनी नाम आज़माएँ।', locale: 'hi', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.loading_more', body: 'Loading…', locale: 'en', sortOrder: 48 },
  { module: AppContentModule.HOME, key: 'markets.search_page.loading_more', body: 'लोड हो रहा है…', locale: 'hi', sortOrder: 48 },
  {
    module: AppContentModule.HOME,
    key: 'company.section_title',
    body: 'Our Company',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.section_title',
    body: 'हमारी कंपनी',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.video_cta',
    body: 'Watch our company introduction',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.video_cta',
    body: 'हमारी कंपनी का परिचय देखें',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.website_cta',
    body: 'Visit website',
    locale: 'en',
    sortOrder: 60,
  },
  {
    module: AppContentModule.HOME,
    key: 'company.website_cta',
    body: 'वेबसाइट देखें',
    locale: 'hi',
    sortOrder: 60,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_label',
    body: 'Add Funds',
    locale: 'en',
    sortOrder: 65,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_label',
    body: 'राशि जोड़ें',
    locale: 'hi',
    sortOrder: 65,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_subtitle',
    body: 'Funding Assistance',
    locale: 'en',
    sortOrder: 70,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.cta_subtitle',
    body: 'जमा सहायता',
    locale: 'hi',
    sortOrder: 70,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.section_title',
    body: 'Market News',
    locale: 'en',
    sortOrder: 75,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.section_title',
    body: 'बाज़ार समाचार',
    locale: 'hi',
    sortOrder: 75,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.empty',
    body: 'Live market news is temporarily unavailable.',
    locale: 'en',
    sortOrder: 80,
  },
  {
    module: AppContentModule.HOME,
    key: 'news.empty',
    body: 'लाइव बाज़ार समाचार अस्थायी रूप से उपलब्ध नहीं है।',
    locale: 'hi',
    sortOrder: 80,
  },
  { module: AppContentModule.HOME, key: 'news.page_empty_title', body: 'Market news is unavailable', locale: 'en', sortOrder: 80 },
  { module: AppContentModule.HOME, key: 'news.page_empty_title', body: 'बाज़ार समाचार उपलब्ध नहीं हैं', locale: 'hi', sortOrder: 80 },
  { module: AppContentModule.HOME, key: 'news.page_empty_body', body: 'Headlines will appear when the market news feed is available.', locale: 'en', sortOrder: 81 },
  { module: AppContentModule.HOME, key: 'news.page_empty_body', body: 'बाज़ार समाचार फ़ीड उपलब्ध होने पर सुर्खियाँ यहाँ दिखाई देंगी।', locale: 'hi', sortOrder: 81 },
  { module: AppContentModule.HOME, key: 'news.refresh', body: 'Refresh', locale: 'en', sortOrder: 82 },
  { module: AppContentModule.HOME, key: 'news.refresh', body: 'रीफ़्रेश करें', locale: 'hi', sortOrder: 82 },
  { module: AppContentModule.HOME, key: 'news.refresh_error', body: 'News could not be updated. Please try again.', locale: 'en', sortOrder: 83 },
  { module: AppContentModule.HOME, key: 'news.refresh_error', body: 'समाचार अपडेट नहीं हो सके। कृपया फिर प्रयास करें।', locale: 'hi', sortOrder: 83 },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_label',
    body: 'Withdraw Funds',
    locale: 'en',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_label',
    body: 'राशि निकालें',
    locale: 'hi',
    sortOrder: 81,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_subtitle',
    body: 'Transfer to Bank',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.withdraw_cta_subtitle',
    body: 'बैंक में स्थानांतरित करें',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_label',
    body: 'Trade',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_label',
    body: 'ट्रेड',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_subtitle',
    body: 'Place orders',
    locale: 'en',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.trade_cta_subtitle',
    body: 'ऑर्डर दें',
    locale: 'hi',
    sortOrder: 82,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.total_asset_label',
    body: 'Total Asset Value',
    locale: 'en',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.total_asset_label',
    body: 'कुल परिसंपत्ति मूल्य',
    locale: 'hi',
    sortOrder: 83,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.available_label',
    body: 'Available Balance',
    locale: 'en',
    sortOrder: 84,
  },
  {
    module: AppContentModule.HOME,
    key: 'funds.available_label',
    body: 'उपलब्ध शेष',
    locale: 'hi',
    sortOrder: 84,
  },
  {
    module: AppContentModule.HOME,
    key: 'indices.section_title',
    body: 'Market Indices',
    locale: 'en',
    sortOrder: 85,
  },
  {
    module: AppContentModule.HOME,
    key: 'indices.section_title',
    body: 'बाज़ार सूचकांक',
    locale: 'hi',
    sortOrder: 85,
  },
  {
    module: AppContentModule.HOME,
    key: 'view_all_cta',
    body: 'View All',
    locale: 'en',
    sortOrder: 86,
  },
  {
    module: AppContentModule.HOME,
    key: 'view_all_cta',
    body: 'सभी देखें',
    locale: 'hi',
    sortOrder: 86,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.page_title',
    body: 'Profile',
    locale: 'en',
    sortOrder: 90,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.page_title',
    body: 'प्रोफ़ाइल',
    locale: 'hi',
    sortOrder: 90,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.overview',
    body: 'Account Overview',
    locale: 'en',
    sortOrder: 91,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.overview',
    body: 'खाता अवलोकन',
    locale: 'hi',
    sortOrder: 91,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.account',
    body: 'Account',
    locale: 'en',
    sortOrder: 92,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.account',
    body: 'खाता',
    locale: 'hi',
    sortOrder: 92,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.funds',
    body: 'Funds',
    locale: 'en',
    sortOrder: 93,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.funds',
    body: 'फंड',
    locale: 'hi',
    sortOrder: 93,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.security',
    body: 'Security',
    locale: 'en',
    sortOrder: 94,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.security',
    body: 'सुरक्षा',
    locale: 'hi',
    sortOrder: 94,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.preferences',
    body: 'Preferences',
    locale: 'en',
    sortOrder: 95,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.preferences',
    body: 'प्राथमिकताएँ',
    locale: 'hi',
    sortOrder: 95,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.support',
    body: 'Support & Education',
    locale: 'en',
    sortOrder: 96,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.support',
    body: 'सहायता और शिक्षा',
    locale: 'hi',
    sortOrder: 96,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.legal',
    body: 'Legal',
    locale: 'en',
    sortOrder: 97,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.section.legal',
    body: 'कानूनी',
    locale: 'hi',
    sortOrder: 97,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.available',
    body: 'Available Balance',
    locale: 'en',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.available',
    body: 'उपलब्ध शेष',
    locale: 'hi',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.portfolio',
    body: 'Product Holdings',
    locale: 'en',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.portfolio',
    body: 'उत्पाद होल्डिंग',
    locale: 'hi',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.returns',
    body: 'Total Returns',
    locale: 'en',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.metric.returns',
    body: 'कुल रिटर्न',
    locale: 'hi',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.title',
    body: 'Help & Support',
    locale: 'en',
    sortOrder: 98,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.title',
    body: 'सहायता और समर्थन',
    locale: 'hi',
    sortOrder: 98,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.subtitle',
    body: 'FAQs, contact support and raise a ticket',
    locale: 'en',
    sortOrder: 99,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.help.subtitle',
    body: 'प्रश्नोत्तर, सहायता से संपर्क और टिकट',
    locale: 'hi',
    sortOrder: 99,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.title',
    body: 'Wealth Insights',
    locale: 'en',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.title',
    body: 'वेल्थ इनसाइट्स',
    locale: 'hi',
    sortOrder: 100,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.subtitle',
    body: 'Knowledge for informed investment decisions',
    locale: 'en',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.insights.subtitle',
    body: 'सूचित निवेश निर्णयों के लिए ज्ञान',
    locale: 'hi',
    sortOrder: 101,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.title',
    body: 'About Us',
    locale: 'en',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.title',
    body: 'हमारे बारे में',
    locale: 'hi',
    sortOrder: 102,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.subtitle',
    body: 'About our app, terms and policies',
    locale: 'en',
    sortOrder: 103,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.about.subtitle',
    body: 'ऐप, नियम और नीतियाँ',
    locale: 'hi',
    sortOrder: 103,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.risk.title',
    body: 'Risk Disclosure',
    locale: 'en',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.risk.title',
    body: 'जोखिम प्रकटीकरण',
    locale: 'hi',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.terms.title',
    body: 'Terms & Conditions',
    locale: 'en',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.terms.title',
    body: 'नियम और शर्तें',
    locale: 'hi',
    sortOrder: 104,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.privacy.title',
    body: 'Privacy Policy',
    locale: 'en',
    sortOrder: 105,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.tile.privacy.title',
    body: 'गोपनीयता नीति',
    locale: 'hi',
    sortOrder: 105,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_label',
    body: 'Logout',
    locale: 'en',
    sortOrder: 106,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_label',
    body: 'लॉग आउट',
    locale: 'hi',
    sortOrder: 106,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_subtitle',
    body: 'Securely logout from your account',
    locale: 'en',
    sortOrder: 107,
  },
  {
    module: AppContentModule.HOME,
    key: 'profile.logout_subtitle',
    body: 'अपने खाते से सुरक्षित रूप से लॉग आउट करें',
    locale: 'hi',
    sortOrder: 107,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.dialog_title',
    body: 'Withdrawal Request',
    locale: 'en',
    sortOrder: 110,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.dialog_title',
    body: 'निकासी अनुरोध',
    locale: 'hi',
    sortOrder: 110,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.available_label',
    body: 'Available Funds',
    locale: 'en',
    sortOrder: 111,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.available_label',
    body: 'उपलब्ध राशि',
    locale: 'hi',
    sortOrder: 111,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.frozen_template',
    body: 'Total frozen: {amount}',
    locale: 'en',
    sortOrder: 112,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.frozen_template',
    body: 'कुल रोकी गई राशि: {amount}',
    locale: 'hi',
    sortOrder: 112,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.amount_label',
    body: 'Withdrawal Amount',
    locale: 'en',
    sortOrder: 113,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.amount_label',
    body: 'निकासी राशि',
    locale: 'hi',
    sortOrder: 113,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_hint',
    body: 'Minimum withdrawal: ₹100',
    locale: 'en',
    sortOrder: 114,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_hint',
    body: 'न्यूनतम निकासी: ₹100',
    locale: 'hi',
    sortOrder: 114,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_label',
    body: 'Withdrawal PIN',
    locale: 'en',
    sortOrder: 115,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_label',
    body: 'निकासी पिन',
    locale: 'hi',
    sortOrder: 115,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_section_title',
    body: 'Withdrawal Bank Account',
    locale: 'en',
    sortOrder: 116,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_section_title',
    body: 'निकासी बैंक खाता',
    locale: 'hi',
    sortOrder: 116,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_picker_label',
    body: 'Bank account',
    locale: 'en',
    sortOrder: 117,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_picker_label',
    body: 'बैंक खाता',
    locale: 'hi',
    sortOrder: 117,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.holder_label',
    body: 'Account Holder',
    locale: 'en',
    sortOrder: 118,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.holder_label',
    body: 'खाताधारक',
    locale: 'hi',
    sortOrder: 118,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.account_label',
    body: 'Bank Account',
    locale: 'en',
    sortOrder: 119,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.account_label',
    body: 'बैंक खाता संख्या',
    locale: 'hi',
    sortOrder: 119,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.status_label',
    body: 'Bank Status',
    locale: 'en',
    sortOrder: 120,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.status_label',
    body: 'बैंक स्थिति',
    locale: 'hi',
    sortOrder: 120,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.notice',
    body: 'Your withdrawal request will be submitted for review. The requested amount is frozen immediately. Approval deducts it from your cash balance; rejection releases it.',
    locale: 'en',
    sortOrder: 121,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.notice',
    body: 'आपका निकासी अनुरोध समीक्षा के लिए भेजा जाएगा। अनुरोधित राशि तुरंत रोक दी जाती है। स्वीकृति पर नकदी से कटती है; अस्वीकृति पर मुक्त होती है।',
    locale: 'hi',
    sortOrder: 121,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.records_title',
    body: 'Withdrawal Records',
    locale: 'en',
    sortOrder: 122,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.records_title',
    body: 'निकासी रिकॉर्ड',
    locale: 'hi',
    sortOrder: 122,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.cancel',
    body: 'Cancel',
    locale: 'en',
    sortOrder: 123,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.cancel',
    body: 'रद्द करें',
    locale: 'hi',
    sortOrder: 123,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.submit',
    body: 'Submit Request',
    locale: 'en',
    sortOrder: 124,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.submit',
    body: 'अनुरोध जमा करें',
    locale: 'hi',
    sortOrder: 124,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_incomplete',
    body: 'Complete your bank account details before withdrawing',
    locale: 'en',
    sortOrder: 125,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_incomplete',
    body: 'निकासी से पहले बैंक खाते का विवरण पूरा करें',
    locale: 'hi',
    sortOrder: 125,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.submitting',
    body: 'A withdrawal request is being submitted',
    locale: 'en',
    sortOrder: 126,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.submitting',
    body: 'निकासी अनुरोध जमा किया जा रहा है',
    locale: 'hi',
    sortOrder: 126,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_error',
    body: 'Minimum withdrawal amount is ₹100',
    locale: 'en',
    sortOrder: 127,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.min_error',
    body: 'न्यूनतम निकासी राशि ₹100 है',
    locale: 'hi',
    sortOrder: 127,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.max_error_template',
    body: 'Maximum available: {amount}',
    locale: 'en',
    sortOrder: 128,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.max_error_template',
    body: 'अधिकतम उपलब्ध: {amount}',
    locale: 'hi',
    sortOrder: 128,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_error',
    body: 'Select a complete bank account',
    locale: 'en',
    sortOrder: 129,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.bank_error',
    body: 'पूरा बैंक खाता चुनें',
    locale: 'hi',
    sortOrder: 129,
  },

  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_error',
    body: 'Enter a 6-digit PIN',
    locale: 'en',
    sortOrder: 130,
  },
  {
    module: AppContentModule.HOME,
    key: 'withdraw.pin_error',
    body: '6 अंकों का पिन दर्ज करें',
    locale: 'hi',
    sortOrder: 130,
  },

  // DEPOSIT (copy only — no receiving / bank accounts)
  {
    module: AppContentModule.DEPOSIT,
    key: 'hero_title',
    body: 'Fund your trading account',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'hero_title',
    body: 'अपने ट्रेडिंग खाते में राशि जोड़ें',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'instructions',
    title: 'Deposit instructions',
    body: 'Contact support for payment details, then transfer. Finance credits your trading balance after payment is confirmed. Deposits are not submitted inside the app.',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'instructions',
    title: 'जमा निर्देश',
    body: 'कृपया जमा निर्देशों के लिए ऑनलाइन सहायता से संपर्क करें। भुगतान की पुष्टि के बाद वित्त टीम आपके खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'cta_label',
    body: 'Contact customer support',
    locale: 'en',
    sortOrder: 15,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'cta_label',
    body: 'ग्राहक सहायता से संपर्क करें',
    locale: 'hi',
    sortOrder: 15,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'chat_preset',
    body: 'Hello, I have completed / want to make a deposit. Please share payment details. Finance will credit my account after confirmation.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'chat_preset',
    body: 'नमस्ते, मैं जमा करना चाहता/चाहती हूँ। कृपया भुगतान विवरण दें। पुष्टि के बाद वित्त टीम खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'api_reject_message',
    body: 'Contact support for payment details, then transfer. Finance credits your trading balance after payment is confirmed. Deposits are not submitted inside the app.',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'api_reject_message',
    body: 'कृपया जमा निर्देशों के लिए ऑनलाइन सहायता से संपर्क करें। भुगतान की पुष्टि के बाद वित्त टीम आपके खाते में राशि जमा करेगी।',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_empty',
    body: 'No deposit records yet.',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_empty',
    body: 'अभी कोई जमा रिकॉर्ड नहीं है।',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms',
    body: '• Verify the beneficiary details with Online Customer Service before transferring.\n\n• Deposits are credited only after finance confirmation.\n\n• Keep your transfer receipt for settlement support.',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms',
    body: '• स्थानांतरण से पहले ऑनलाइन ग्राहक सेवा से लाभार्थी विवरण सत्यापित करें।\n\n• वित्त पुष्टि के बाद ही जमा जमा होती है।\n\n• निपटान सहायता के लिए स्थानांतरण रसीद सुरक्षित रखें।',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'page_title',
    body: 'Deposit',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'page_title',
    body: 'जमा',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_section_title',
    body: 'DEPOSIT HISTORY',
    locale: 'en',
    sortOrder: 56,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'history_section_title',
    body: 'जमा इतिहास',
    locale: 'hi',
    sortOrder: 56,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms_section_title',
    body: 'TERMS',
    locale: 'en',
    sortOrder: 57,
  },
  {
    module: AppContentModule.DEPOSIT,
    key: 'terms_section_title',
    body: 'शर्तें',
    locale: 'hi',
    sortOrder: 57,
  },

  // SUPPORT (customer-facing en/hi + ops zh)
  {
    module: AppContentModule.SUPPORT,
    key: 'header_title',
    body: 'Online Customer Service',
    locale: 'en',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'header_title',
    body: 'ऑनलाइन ग्राहक सेवा',
    locale: 'hi',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'fab_label',
    body: 'Customer Service',
    locale: 'en',
    sortOrder: 6,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'fab_label',
    body: 'ग्राहक सेवा',
    locale: 'hi',
    sortOrder: 6,
  },

  {
    module: AppContentModule.SUPPORT,
    key: 'greeting',
    body: 'You are contacting online customer service inside the app.',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'greeting',
    body: 'आप ऐप के अंदर ऑनलाइन ग्राहक सेवा से संपर्क कर रहे हैं।',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'hours',
    body: 'Online customer service hours: Mon-Sun 09:00-22:00 (IST). We are here to help with deposits, trading and account questions.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'hours',
    body: 'ऑनलाइन ग्राहक सेवा समय: सोम-रवि 09:00-22:00 (IST)। जमा, ट्रेडिंग और खाते में सहायता के लिए हम उपलब्ध हैं।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_topics_label',
    body: 'Quick topics',
    locale: 'en',
    sortOrder: 22,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_topics_label',
    body: 'त्वरित विषय',
    locale: 'hi',
    sortOrder: 22,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.deposit',
    body: 'Deposit',
    locale: 'en',
    sortOrder: 24,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.deposit',
    body: 'जमा',
    locale: 'hi',
    sortOrder: 24,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.trading',
    body: 'Trading',
    locale: 'en',
    sortOrder: 25,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.trading',
    body: 'ट्रेडिंग',
    locale: 'hi',
    sortOrder: 25,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.account',
    body: 'Account',
    locale: 'en',
    sortOrder: 26,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'topic.account',
    body: 'खाता',
    locale: 'hi',
    sortOrder: 26,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'composer_hint',
    body: 'Use a topic or open on mobile',
    locale: 'en',
    sortOrder: 28,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'composer_hint',
    body: 'विषय चुनें या मोबाइल पर खोलें',
    locale: 'hi',
    sortOrder: 28,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.help',
    body: 'Hello, I need help with my account.',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.help',
    body: 'नमस्ते, मुझे अपने खाते में सहायता चाहिए।',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.deposit',
    body: 'Hello, I have completed / want to make a deposit. Please share payment details. Finance will credit my account after confirmation.',
    locale: 'en',
    sortOrder: 35,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'chat_preset.deposit',
    body: 'नमस्ते, मैं अपने खाते में पैसे जोड़ना चाहता/चाहती हूँ।',
    locale: 'hi',
    sortOrder: 35,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'salesmartly_script_url',
    // Intentionally empty: production must set CMS or SALESMARTLY_SCRIPT_URL.
    // Do not ship a concrete tenant project_*.js as a silent fallback.
    body: '',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'salesmartly_script_url',
    body: '',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'tags',
    body: '入金咨询,提现问题,KYC,交易问题,账户问题,紧急,已跟进',
    locale: 'zh',
    sortOrder: 5,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.deposit',
    title: '入金指引',
    body: '您好，请按客服提供的存款方式付款并发送付款凭证。客服会转交信息，财务核实实际到账后为账户上分。',
    locale: 'zh',
    sortOrder: 50,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.withdrawal',
    title: '提现跟进',
    body: '您的提现申请已收到，财务会根据订单号核对并处理。',
    locale: 'zh',
    sortOrder: 60,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.kyc',
    title: 'KYC 审核',
    body: '请上传清晰的 Aadhaar 或 PAN 文件，业务员会尽快审核 KYC。',
    locale: 'zh',
    sortOrder: 70,
  },
  {
    module: AppContentModule.SUPPORT,
    key: 'quick_reply.general',
    title: '通用核查',
    body: '请提供手机号、客户姓名和问题截图，我们马上为您核查。',
    locale: 'zh',
    sortOrder: 80,
  },
  // TRADING
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_title',
    body: 'No institutional offers available',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_title',
    body: 'कोई संस्थागत प्रस्ताव उपलब्ध नहीं',
    locale: 'hi',
    sortOrder: 10,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_subtitle',
    body: 'Stocks will appear here when live market data is available.',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.TRADING,
    key: 'institutional.empty_subtitle',
    body: 'लाइव बाज़ार डेटा उपलब्ध होने पर शेयर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 20,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_title',
    body: 'No OTC opportunities available',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_title',
    body: 'कोई ओटीसी अवसर उपलब्ध नहीं',
    locale: 'hi',
    sortOrder: 30,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_subtitle',
    body: 'Backend-approved opportunities will appear here during the trading session.',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.TRADING,
    key: 'otc.empty_subtitle',
    body: 'ट्रेडिंग सत्र में बैकएंड द्वारा स्वीकृत अवसर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 40,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.confirm_template',
    body: 'Submit IPO application {current} of {max}?\n\nPayment is automatic after allotment if your account has sufficient funds.',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.confirm_template',
    body: 'आईपीओ आवेदन {current}/{max} जमा करें?\n\nआवंटन के बाद यदि खाते में पर्याप्त राशि है तो भुगतान स्वचालित होगा।',
    locale: 'hi',
    sortOrder: 50,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_title',
    body: 'No IPOs open for application',
    locale: 'en',
    sortOrder: 52,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_title',
    body: 'आवेदन के लिए कोई आईपीओ खुला नहीं',
    locale: 'hi',
    sortOrder: 52,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_subtitle',
    body: 'New IPO opportunities will appear here when applications open.',
    locale: 'en',
    sortOrder: 53,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_open_subtitle',
    body: 'आवेदन खुलने पर नए आईपीओ अवसर यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 53,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_title',
    body: 'No IPO records',
    locale: 'en',
    sortOrder: 54,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_title',
    body: 'कोई आईपीओ रिकॉर्ड नहीं',
    locale: 'hi',
    sortOrder: 54,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_subtitle',
    body: 'Your IPO applications and available offers will appear here.',
    locale: 'en',
    sortOrder: 55,
  },
  {
    module: AppContentModule.TRADING,
    key: 'ipo.empty_subtitle',
    body: 'आपके आईपीओ आवेदन और उपलब्ध प्रस्ताव यहाँ दिखेंगे।',
    locale: 'hi',
    sortOrder: 55,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_title',
    body: 'No investments yet',
    locale: 'en',
    sortOrder: 56,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_title',
    body: 'अभी कोई निवेश नहीं',
    locale: 'hi',
    sortOrder: 56,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_subtitle',
    body: 'No Institutional, OTC or IPO holdings yet.',
    locale: 'en',
    sortOrder: 57,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.empty_subtitle',
    body: 'अभी कोई संस्थागत, ओटीसी या आईपीओ होल्डिंग नहीं है।',
    locale: 'hi',
    sortOrder: 57,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.explore_cta',
    body: 'Explore offers',
    locale: 'en',
    sortOrder: 58,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.explore_cta',
    body: 'प्रस्ताव देखें',
    locale: 'hi',
    sortOrder: 58,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_title',
    body: 'Portfolio',
    locale: 'en',
    sortOrder: 59,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_title',
    body: 'पोर्टफोलियो',
    locale: 'hi',
    sortOrder: 59,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_subtitle',
    body: 'Institutional · OTC · IPO',
    locale: 'en',
    sortOrder: 590,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.page_subtitle',
    body: 'Institutional · OTC · IPO',
    locale: 'hi',
    sortOrder: 590,
  },
  { module: AppContentModule.TRADING, key: 'portfolio.loading', body: 'Loading portfolio', locale: 'en', sortOrder: 591 },
  { module: AppContentModule.TRADING, key: 'portfolio.loading', body: 'पोर्टफोलियो लोड हो रहा है', locale: 'hi', sortOrder: 591 },
  { module: AppContentModule.TRADING, key: 'portfolio.load_error_title', body: 'Unable to load portfolio', locale: 'en', sortOrder: 592 },
  { module: AppContentModule.TRADING, key: 'portfolio.load_error_title', body: 'पोर्टफोलियो लोड नहीं हो सका', locale: 'hi', sortOrder: 592 },
  { module: AppContentModule.TRADING, key: 'portfolio.recent_activity', body: 'Recent Activity', locale: 'en', sortOrder: 650 },
  { module: AppContentModule.TRADING, key: 'portfolio.recent_activity', body: 'हाल की गतिविधि', locale: 'hi', sortOrder: 650 },
  { module: AppContentModule.TRADING, key: 'portfolio.view_details', body: 'View Details', locale: 'en', sortOrder: 651 },
  { module: AppContentModule.TRADING, key: 'portfolio.view_details', body: 'विवरण देखें', locale: 'hi', sortOrder: 651 },
  { module: AppContentModule.TRADING, key: 'portfolio.close', body: 'Close', locale: 'en', sortOrder: 652 },
  { module: AppContentModule.TRADING, key: 'portfolio.close', body: 'बंद करें', locale: 'hi', sortOrder: 652 },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.value_label',
    body: 'Total Portfolio Value',
    locale: 'en',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.value_label',
    body: 'कुल पोर्टफोलियो मूल्य',
    locale: 'hi',
    sortOrder: 591,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.summary_heading',
    body: 'Investment Summary',
    locale: 'en',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.summary_heading',
    body: 'निवेश सारांश',
    locale: 'hi',
    sortOrder: 592,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.allocation_heading',
    body: 'Asset Allocation',
    locale: 'en',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.allocation_heading',
    body: 'परिसंपत्ति आवंटन',
    locale: 'hi',
    sortOrder: 593,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.quantity',
    body: 'Quantity',
    locale: 'en',
    sortOrder: 594,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.available',
    body: 'Available',
    locale: 'en',
    sortOrder: 595,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.average_cost',
    body: 'Average cost',
    locale: 'en',
    sortOrder: 596,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_value',
    body: 'Current value',
    locale: 'en',
    sortOrder: 597,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.unrealized_pnl',
    body: 'Unrealized P&L',
    locale: 'en',
    sortOrder: 598,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.frozen',
    body: 'Frozen',
    locale: 'en',
    sortOrder: 599,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.current_price',
    body: 'Current price',
    locale: 'en',
    sortOrder: 600,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.invested',
    body: 'Invested',
    locale: 'en',
    sortOrder: 601,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.realized_pnl',
    body: 'Realized P&L',
    locale: 'en',
    sortOrder: 602,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.day_pnl',
    body: 'Day P&L',
    locale: 'en',
    sortOrder: 603,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_cost',
    body: 'Valued at cost. Market quote unavailable.',
    locale: 'en',
    sortOrder: 604,
  },
  {
    module: AppContentModule.TRADING,
    key: 'portfolio.detail.valuation_market',
    body: 'Valued from the current market quote in this response.',
    locale: 'en',
    sortOrder: 605,
  },
  {
    module: AppContentModule.TRADING,
    key: 'state.data_unavailable',
    body: 'Trading data is temporarily unavailable.',
    locale: 'en',
    sortOrder: 606,
  },
  { module: AppContentModule.TRADING, key: 'state.loading', body: 'Loading trading data', locale: 'en', sortOrder: 606.5 },
  {
    module: AppContentModule.TRADING,
    key: 'orders.clear_filters',
    body: 'Clear filters',
    locale: 'en',
    sortOrder: 607,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_title',
    body: 'No matching orders',
    locale: 'en',
    sortOrder: 608,
  },
  {
    module: AppContentModule.TRADING,
    key: 'orders.empty_message',
    body: 'Nothing in the currently loaded orders matches these filters.',
    locale: 'en',
    sortOrder: 609,
  },
  { module: AppContentModule.TRADING, key: 'action.buy', body: 'Buy', locale: 'en', sortOrder: 610 },
  { module: AppContentModule.TRADING, key: 'action.sell', body: 'Sell', locale: 'en', sortOrder: 611 },
  { module: AppContentModule.TRADING, key: 'action.retry', body: 'Retry', locale: 'en', sortOrder: 612 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.quantity', body: 'मात्रा', locale: 'hi', sortOrder: 594 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.available', body: 'उपलब्ध', locale: 'hi', sortOrder: 595 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.average_cost', body: 'औसत लागत', locale: 'hi', sortOrder: 596 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.current_value', body: 'वर्तमान मूल्य', locale: 'hi', sortOrder: 597 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.unrealized_pnl', body: 'अवास्तविक लाभ/हानि', locale: 'hi', sortOrder: 598 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.frozen', body: 'फ्रीज़ की गई', locale: 'hi', sortOrder: 599 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.current_price', body: 'वर्तमान कीमत', locale: 'hi', sortOrder: 600 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.invested', body: 'निवेशित', locale: 'hi', sortOrder: 601 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.realized_pnl', body: 'वास्तविक लाभ/हानि', locale: 'hi', sortOrder: 602 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.day_pnl', body: 'आज का लाभ/हानि', locale: 'hi', sortOrder: 603 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.valuation_cost', body: 'लागत पर मूल्यांकन। बाजार भाव उपलब्ध नहीं है।', locale: 'hi', sortOrder: 604 },
  { module: AppContentModule.TRADING, key: 'portfolio.detail.valuation_market', body: 'इस प्रतिक्रिया में वर्तमान बाजार भाव के आधार पर मूल्यांकन किया गया है।', locale: 'hi', sortOrder: 605 },
  { module: AppContentModule.TRADING, key: 'state.data_unavailable', body: 'ट्रेडिंग डेटा अस्थायी रूप से उपलब्ध नहीं है।', locale: 'hi', sortOrder: 606 },
  { module: AppContentModule.TRADING, key: 'state.loading', body: 'ट्रेडिंग डेटा लोड हो रहा है', locale: 'hi', sortOrder: 606.5 },
  { module: AppContentModule.TRADING, key: 'orders.clear_filters', body: 'फ़िल्टर साफ़ करें', locale: 'hi', sortOrder: 607 },
  { module: AppContentModule.TRADING, key: 'orders.empty_title', body: 'कोई मेल खाता ऑर्डर नहीं', locale: 'hi', sortOrder: 608 },
  { module: AppContentModule.TRADING, key: 'orders.empty_message', body: 'वर्तमान में लोड किए गए किसी ऑर्डर से ये फ़िल्टर मेल नहीं खाते।', locale: 'hi', sortOrder: 609 },
  { module: AppContentModule.TRADING, key: 'action.buy', body: 'खरीदें', locale: 'hi', sortOrder: 610 },
  { module: AppContentModule.TRADING, key: 'action.sell', body: 'बेचें', locale: 'hi', sortOrder: 611 },
  { module: AppContentModule.TRADING, key: 'action.retry', body: 'पुनः प्रयास करें', locale: 'hi', sortOrder: 612 },

  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_title',
    body: 'No holdings',
    locale: 'en',
    sortOrder: 85,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_title',
    body: 'कोई होल्डिंग नहीं है',
    locale: 'hi',
    sortOrder: 85,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_subtitle',
    body: 'Your holdings will appear here after settled positions are added.',
    locale: 'en',
    sortOrder: 86,
  },
  {
    module: AppContentModule.TRADING,
    key: 'holdings.empty_subtitle',
    body: 'निपटान के बाद होल्डिंग यहाँ दिखेंगी।',
    locale: 'hi',
    sortOrder: 86,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.trades',
    body: 'Trades',
    locale: 'en',
    sortOrder: 610,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.trades',
    body: 'ट्रेड्स',
    locale: 'hi',
    sortOrder: 610,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.institutional',
    body: 'Institutional',
    locale: 'en',
    sortOrder: 611,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.institutional',
    body: 'संस्थागत',
    locale: 'hi',
    sortOrder: 611,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.holdings',
    // Stable legacy key retained for compatibility — display label is Positions.
    body: 'Positions',
    locale: 'en',
    sortOrder: 612,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.holdings',
    body: 'पोजीशन',
    locale: 'hi',
    sortOrder: 612,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.pending',
    body: 'Pending',
    locale: 'en',
    sortOrder: 613,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.pending',
    body: 'लंबित',
    locale: 'hi',
    sortOrder: 613,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.order_book',
    body: 'Order Book',
    locale: 'en',
    sortOrder: 614,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.order_book',
    body: 'ऑर्डर बुक',
    locale: 'hi',
    sortOrder: 614,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.otc',
    body: 'OTC',
    locale: 'en',
    sortOrder: 615,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.otc',
    body: 'ओटीसी',
    locale: 'hi',
    sortOrder: 615,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.ipo',
    body: 'IPO',
    locale: 'en',
    sortOrder: 616,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.ipo',
    body: 'आईपीओ',
    locale: 'hi',
    sortOrder: 616,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.history',
    body: 'History',
    locale: 'en',
    sortOrder: 617,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.history',
    body: 'इतिहास',
    locale: 'hi',
    sortOrder: 617,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.funds_ledger',
    body: 'Funds Ledger',
    locale: 'en',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.funds_ledger',
    body: 'राशि लेजर',
    locale: 'hi',
    sortOrder: 618,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.all',
    // Stable legacy key retained for compatibility — display label is Overview.
    body: 'Overview',
    locale: 'en',
    sortOrder: 619,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.all',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 619,
  },

  {
    module: AppContentModule.TRADING,
    key: 'tab.ins_stock',
    body: 'Ins. Stock',
    locale: 'en',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'tab.ins_stock',
    body: 'संस्थागत शेयर',
    locale: 'hi',
    sortOrder: 620,
  },

  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'Overview',
    locale: 'en',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 618,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'Overview',
    locale: 'en',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.overview',
    body: 'अवलोकन',
    locale: 'hi',
    sortOrder: 620,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.orders',
    body: 'Orders',
    locale: 'en',
    sortOrder: 621,
  },
  {
    module: AppContentModule.TRADING,
    key: 'shortcut.orders',
    body: 'ऑर्डर',
    locale: 'hi',
    sortOrder: 621,
  },

  {
    module: AppContentModule.TRADING,
    key: 'guide.institutional',
    title: 'Institutional offers',
    body: 'Institutional stocks settle at the live market price. Review eligibility and terms before trading.',
    locale: 'en',
    sortOrder: 60,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.institutional',
    title: 'संस्थागत प्रस्ताव',
    body: 'संस्थागत शेयर लाइव बाज़ार कीमत पर निपटाए जाते हैं। ट्रेड से पहले पात्रता और शर्तें देखें।',
    locale: 'hi',
    sortOrder: 60,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.otc',
    title: 'OTC trading',
    body: 'The market quote is for reference only. Purchases settle at the discount settlement price shown in the trade dialog. Enter quantity and the 4-digit transaction key; orders stay Pending Review until approved and appear in holdings only after approval.',
    locale: 'en',
    sortOrder: 70,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.otc',
    title: 'ओटीसी ट्रेडिंग',
    body: 'बाज़ार भाव केवल संदर्भ के लिए है। खरीद ट्रेड डायलॉग में दिखाए गए डिस्काउंट निपटान मूल्य पर होती है। मात्रा और 4 अंकों की लेनदेन कुंजी दर्ज करें; स्वीकृति तक समीक्षा लंबित रहती है और उसके बाद ही होल्डिंग में दिखती है।',
    locale: 'hi',
    sortOrder: 70,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.ipo',
    title: 'IPO applications',
    body: 'IPO applications may be pending, allocated or rejected. An allocation can create an outstanding payment obligation. Check notices before assuming shares are sellable.',
    locale: 'en',
    sortOrder: 80,
  },
  {
    module: AppContentModule.TRADING,
    key: 'guide.ipo',
    title: 'आईपीओ आवेदन',
    body: 'आईपीओ आवेदन लंबित, आवंटित या अस्वीकृत हो सकता है। आवंटन पर भुगतान बकाया हो सकता है। शेयर बेचने योग्य मानने से पहले सूचनाएँ जाँचें।',
    locale: 'hi',
    sortOrder: 80,
  },
  {
    module: AppContentModule.LEGAL,
    key: 'privacy.document',
    title: 'Privacy Policy',
    body: JSON.stringify(privacyDocument),
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.LEGAL,
    key: 'terms.document',
    title: 'Terms of Service',
    body: JSON.stringify(termsDocument),
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.LEGAL,
    key: 'risk.document',
    title: 'Risk Disclosure',
    body: JSON.stringify(riskDocument),
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'company_name',
    body: 'India Trading App',
    locale: 'en',
    sortOrder: 10,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'legal_name',
    body: '',
    locale: 'en',
    sortOrder: 20,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'registered_address',
    body: '',
    locale: 'en',
    sortOrder: 30,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'grievance_contact',
    body: '',
    locale: 'en',
    sortOrder: 40,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'app_version',
    // Marketing / display label only — not the client PackageInfo / pubspec build.
    body: 'Version 1.0.0',
    locale: 'en',
    sortOrder: 50,
  },
  {
    module: AppContentModule.ABOUT,
    key: 'summary',
    body: 'Professional trading access for equities, institutional offers, OTC and IPOs. Complete legal entity, registered address and grievance contacts before public release.',
    locale: 'en',
    sortOrder: 60,
  },
  {
    module: AppContentModule.INSIGHTS,
    key: 'intro.title',
    body: 'Knowledge for informed investment decisions',
    locale: 'en',
    sortOrder: 1,
  },
  {
    module: AppContentModule.INSIGHTS,
    key: 'intro.title',
    body: 'सूचित निवेश निर्णयों के लिए ज्ञान',
    locale: 'hi',
    sortOrder: 1,
  },
  {
    module: AppContentModule.INSIGHTS,
    key: 'intro.body',
    body: 'Explore essential investment concepts, portfolio strategies, market perspectives and wealth-management principles designed to help investors make more informed financial decisions.',
    locale: 'en',
    sortOrder: 2,
  },
  {
    module: AppContentModule.INSIGHTS,
    key: 'intro.body',
    body: 'निवेश की मूल अवधारणाएँ, पोर्टफोलियो रणनीतियाँ, बाज़ार दृष्टिकोण और संपत्ति प्रबंधन सिद्धांत जानें, ताकि अधिक सूचित वित्तीय निर्णय ले सकें।',
    locale: 'hi',
    sortOrder: 2,
  },
  ...insightArticles.flatMap((article) => [
    {
      module: AppContentModule.INSIGHTS,
      key: article.key,
      title: article.titleEn,
      body: article.bodyEn,
      locale: 'en',
      sortOrder: article.sortOrder,
    },
    {
      module: AppContentModule.INSIGHTS,
      key: article.key,
      title: article.titleHi,
      body: article.bodyHi,
      locale: 'hi',
      sortOrder: article.sortOrder,
    },
  ]),
];
