/** Stable public error codes for financial, approval, and authorization flows. */
export const BUSINESS_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: 'UNAUTHORIZED',
  AUTHORIZATION_DENIED: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'NOT_FOUND',
  REQUEST_CONFLICT: 'CONFLICT',
  WITHDRAWAL_ALREADY_REVIEWED: 'WITHDRAWAL_ALREADY_REVIEWED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  ORDER_IDEMPOTENCY_CONFLICT: 'ORDER_IDEMPOTENCY_CONFLICT',
  FUNDS_INSUFFICIENT: 'FUNDS_INSUFFICIENT',
  APPROVAL_INVALID_STATE: 'APPROVAL_INVALID_STATE',
  KYC_REQUIRED: 'KYC_REQUIRED',
} as const;

export type BusinessErrorCode =
  (typeof BUSINESS_ERROR_CODES)[keyof typeof BUSINESS_ERROR_CODES];
