-- AlterEnum
ALTER TYPE "AppContentModule" ADD VALUE IF NOT EXISTS 'LEGAL';
ALTER TYPE "AppContentModule" ADD VALUE IF NOT EXISTS 'ABOUT';
ALTER TYPE "AppContentModule" ADD VALUE IF NOT EXISTS 'INSIGHTS';
